apiVersion: v1
kind: PersistentVolume
metadata:
  name: shared-shib-pv
  labels:
      type: shared-shib
spec:
  capacity:
    storage: STORAGESHAREDSHIB
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/shared-shibboleth-idp"
    type: DirectoryOrCreate