kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
commonLabels:
  app: nfs-server
images:
  - name: k8s.gcr.io/volume-nfs
    newTag: "0.8"
resources:
  - persistentvolumeclaims.yaml
  - persistentvolumes.yaml
  - replicationcontrollers.yaml
#  - services.yaml