apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-shib-pvc
  labels:
    app: nfs-shared-shib-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: STORAGESHAREDSHIB
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc
  labels:
    app: nfs-pvc
spec:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: "gluu-nfs-sc"
  resources:
    requests:
      storage: STORAGENFS
