apiVersion: v1
kind: PersistentVolume
metadata:
  name: shared-shib-pv
spec:
  capacity:
    storage: STORAGESHAREDSHIB
  accessModes:
    - ReadWriteMany
  nfs:
    server: NFSIP
    path: "/opt/shared-shibboleth-idp"