# FOR POC
apiVersion: kubedb.com/v1alpha1
kind: Redis
metadata:
  name: redis-cluster
  namespace: redis
spec:
  version: 5.0.3-v1
  mode: Cluster
  cluster:
    master: 3
    replicas: 1
  storage:
    storageClassName: "redis-sc"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 8Gi
  monitor:
    agent: prometheus.io/coreos-operator
    prometheus:
      namespace: redis
      labels:
        app: redis-cluster
      interval: 10s
  configSecret:
    configMap:
      name: redis-cluster-configmap
  resources:
    requests:
      memory: "1500Mi"
      cpu: "2500m"
    limits:
      memory: "1500Mi"
      cpu: "2500m"
  terminationPolicy: WipeOut
