apiVersion: v2
name: gluu-upgrade
description: A Helm chart for upgrading gluu server
type: application
version: 1.0.4
appVersion: 4.2.0_dev
maintainers:
- name: Gluu
email: support@gluu.org
home: https://gluu.org/docs/gluu-server