# cnReleaseName is the release name used when deploying main gluu server chart
cnReleaseName: cv # CHANGE

image:
  repository: gluufederation/upgrade
  tag: 5.0.0_dev

resources: {}
  # requests:
  #   memory: 100Mi
  #   cpu: 150m
  # limits:
  #   memory: 100Mi
  #   cpu: 150m

nameOverride: ""
fullnameOverride: ""

configAdapterName: kubernetes
configSecretAdapter: kubernetes
source: "4.0"
target: "4.1"
# domain is the FQDN used in main gluu server chart 
domain: demoexample.gluu.org
# options: ldap/couchbase/hybrid
cnPersistenceType: ldap
# options: default/user/site/cache/statistic
# used only if CN_PERSISTENCE_TYPE is ldap or hybrid
cnPersistenceLdapMapping: default
cnLdapUrl: opendj:1636
# cnCouchbaseUrl is the couchbase service name
cnCouchbaseUrl: cbgluu.default.svc.cluster.local
cnCouchbaseUser: admin
# cnCouchbasePassFile is the location of password file. Should be named `couchbase_password` containing only password file
cnCouchbasePassFile:  /etc/gluu/conf/couchbase_password
# cnCouchbaseCertFile location of
cnCouchbaseCertFile: /etc/certs/couchbase.crt