apiVersion: apps/v1
kind: Deployment
metadata:
  name: radius
spec:
  replicas: 1
  selector:
    matchLabels:
      app: radius
  template:
    spec:
      containers:
      - name: radius
        imagePullPolicy: Always
        image: gluufederation/radius:4.0.0_01
        command:
          - /bin/sh
          - -c
          - |
              /usr/bin/python /scripts/update-lb-ip.py &
              /app/scripts/entrypoint.sh
        volumeMounts:
          - mountPath: /scripts
            name: update-lb-ip
      volumes:
      - name: update-lb-ip
        configMap:
          name: updatelbip