# License terms and conditions for Gluu Cloud Native Edition:
# https://www.apache.org/licenses/LICENSE-2.0
apiVersion: batch/v1
kind: Job
metadata:
  name: configuration-manager-load-job
spec:
  template:
    spec:
      restartPolicy: Never
      volumes:
        - name: config-generate-params
          configMap:
            name: config-generate-params
      containers:
        - name: configuration-manager-load
          image: janssenproject/configuration-manager:5.0.0_dev
          volumeMounts:
            - mountPath: /opt/configuration-manager/db/generate.json
              name: config-generate-params
              subPath: generate.json
          envFrom:
          - configMapRef:
              name: gluu-config-cm
          args: ["load"]