# License terms and conditions for Gluu Cloud Native Edition:
# https://www.apache.org/licenses/LICENSE-2.0
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: configuration-manager-load
resources:
  - jobs.yaml
  - roles.yaml
generatorOptions:
  disableNameSuffixHash: true
images:
  - name: janssenproject/configuration-manager
    newTag: 5.0.0_dev
configMapGenerator:
  - name: gluu-config-cm
    literals:
      - CN_CLIENT_API_SERVER_URL="client-api:8443"
      - CN_CLIENT_API_BIND_IP_ADDRESSES="*"
      - CN_KEY_ROTATION_FORCE="false"
      - CN_SSL_CERT_FROM_SECRETS="true"
      - CN_KEY_ROTATION_CHECK="3600"
      - CN_KEY_ROTATION_INTERVAL="48"
      - CN_LDAP_INIT="true"
      - CN_LDAP_INIT_HOST="opendj"
      - CN_LDAP_INIT_PORT="1636"
      - CN_OXTRUST_CONFIG_GENERATION="true"
      - CN_REDIS_TYPE="STANDALONE"
      - CN_REDIS_URL="redis:6379"
      - CN_CERT_ALT_NAME="opendj"
      #- CN_CACHE_TYPE="REDIS"
      #-  CN_REDIS_URL="redis:6379"
      #-  CN_REDIS_TYPE="STANDALONE
      - CN_MAX_RAM_PERCENTAGE="75.0"
      - CN_SYNC_CASA_MANIFESTS="false"
      - CN_OXTRUST_BACKEND="oxtrust:8080"
      - CN_JACKRABBIT_SYNC_INTERVAL=300
      - CN_JACKRABBIT_URL="http://jackrabbit:8080"
      - CN_CONTAINER_METADATA="kubernetes"
      - CN_SYNC_SHIB_MANIFESTS=false
      - CN_DOCUMENT_STORE_TYPE="JCA"
      - CN_JACKRABBIT_ADMIN_ID="admin"
      - CN_JACKRABBIT_ADMIN_PASSWORD_FILE="/etc/gluu/conf/jackrabbit_admin_password"
      - CN_CACHE_TYPE=CNCACHETYPE
      - CN_OXTRUST_API_ENABLED=CNOXTRUSTAPIENABLED
      - CN_OXTRUST_API_TEST_MODE=CNOXTRUSTAPITESTMODE
      - CN_CASA_ENABLED=CNCASAENABBLED
      - CN_PASSPORT_ENABLED=CNPASSPORTENABLED
      - CN_RADIUS_ENABLED=CNRADIUSENABLED
      - CN_SAML_ENABLED=CNSAMLENABLED
      - CN_CONFIG_KUBERNETES_NAMESPACE="default"
      - CN_SECRET_KUBERNETES_NAMESPACE="default"
      - LB_ADDR=LBADDR
      - CN_CONFIG_ADAPTER="kubernetes"
      - CN_SECRET_ADAPTER="kubernetes"
      - DOMAIN=FQDN
      - CN_AUTH_SERVER_BACKEND="auth-server:8080"
      # options: ldap/couchbase/hybrid
      - CN_PERSISTENCE_TYPE=PERSISTENCETYPE
      # options: default/user/site/cache/statistic; used only if CN_PERSISTENCE_TYPE is hybrid
      - CN_PERSISTENCE_LDAP_MAPPING=LDAPMAPPING
      # used only if CN_PERSISTENCE_TYPE is ldap or hybrid
      - CN_LDAP_URL="opendj:1636"
      # used only if CN_PERSISTENCE_TYPE is couchbase or hybrid
      - CN_COUCHBASE_URL=COUCHBASEURL
      - CN_COUCHBASE_INDEX_NUM_REPLICA="0"
      - CN_COUCHBASE_USER=CBUSER
      - CN_COUCHBASE_SUPERUSER=CBSUPER
      - CN_COUCHBASE_SUPERUSER_PASSWORD_FILE="/etc/gluu/conf/couchbase_superuser_password"
      - CN_COUCHBASE_CERT_FILE="/etc/certs/couchbase.crt"
      - CN_COUCHBASE_PASSWORD_FILE="/etc/gluu/conf/couchbase_password"
      - CN_CLIENT_API_APPLICATION_CERT_CN="client-api"
      - CN_CLIENT_API_ADMIN_CERT_CN="client-api"
  - name: config-generate-params
    files:
      - generate.json
