# License terms and conditions for Gluu Cloud Native Edition:
# https://www.apache.org/licenses/LICENSE-2.0
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: configuration-manager-load
resources:
  - jobs.yaml
  - roles.yaml
generatorOptions:
  disableNameSuffixHash: true
images:
  - name: janssenproject/configuration-manager
    newTag: 5.0.0_dev
configMapGenerator:
  - name: gluu-config-cm
    literals:
      - JANS_CLIENT_API_SERVER_URL="client-api:8443"
      - JANS_CLIENT_API_BIND_IP_ADDRESSES="*"
      - JANS_KEY_ROTATION_FORCE="false"
      - JANS_SSL_CERT_FROM_SECRETS="true"
      - JANS_KEY_ROTATION_CHECK="3600"
      - JANS_KEY_ROTATION_INTERVAL="48"
      - JANS_LDAP_INIT="true"
      - JANS_LDAP_INIT_HOST="opendj"
      - JANS_LDAP_INIT_PORT="1636"
      - JANS_OXTRUST_CONFIG_GENERATION="true"
      - JANS_REDIS_TYPE="STANDALONE"
      - JANS_REDIS_URL="redis:6379"
      - JANS_CERT_ALT_NAME="opendj"
      #- JANS_CACHE_TYPE="REDIS"
      #-  JANS_REDIS_URL="redis:6379"
      #-  JANS_REDIS_TYPE="STANDALONE
      - JANS_MAX_RAM_PERCENTAGE="75.0"
      - JANS_SYNC_CASA_MANIFESTS="false"
      - JANS_OXTRUST_BACKEND="oxtrust:8080"
      - JANS_JACKRABBIT_SYNC_INTERVAL=300
      - JANS_JACKRABBIT_URL="http://jackrabbit:8080"
      - JANS_CONTAINER_METADATA="kubernetes"
      - JANS_SYNC_SHIB_MANIFESTS=false
      - JANS_DOCUMENT_STORE_TYPE="JCA"
      - JANS_JACKRABBIT_ADMIN_ID="admin"
      - JANS_JACKRABBIT_ADMIN_PASSWORD_FILE="/etc/gluu/conf/jackrabbit_admin_password"
      - JANS_CACHE_TYPE=GLUUCACHETYPE
      - JANS_OXTRUST_API_ENABLED=GLUUOXTRUSTAPIENABLED
      - JANS_OXTRUST_API_TEST_MODE=GLUUOXTRUSTAPITESTMODE
      - JANS_CASA_ENABLED=GLUUCASAENABBLED
      - JANS_PASSPORT_ENABLED=GLUUPASSPORTENABLED
      - JANS_RADIUS_ENABLED=GLUURADIUSENABLED
      - JANS_SAML_ENABLED=GLUUSAMLENABLED
      - JANS_CONFIG_KUBERNETES_NAMESPACE="default"
      - JANS_SECRET_KUBERNETES_NAMESPACE="default"
      - LB_ADDR=LBADDR
      - JANS_CONFIG_ADAPTER="kubernetes"
      - JANS_SECRET_ADAPTER="kubernetes"
      - DOMAIN=FQDN
      - JANS_AUTH_SERVER_BACKEND="auth-server:8080"
      # options: ldap/couchbase/hybrid
      - JANS_PERSISTENCE_TYPE=PERSISTENCETYPE
      # options: default/user/site/cache/statistic; used only if JANS_PERSISTENCE_TYPE is hybrid
      - JANS_PERSISTENCE_LDAP_MAPPING=LDAPMAPPING
      # used only if JANS_PERSISTENCE_TYPE is ldap or hybrid
      - JANS_LDAP_URL="opendj:1636"
      # used only if JANS_PERSISTENCE_TYPE is couchbase or hybrid
      - JANS_COUCHBASE_URL=COUCHBASEURL
      - JANS_COUCHBASE_USER=CBUSER
      - JANS_COUCHBASE_SUPERUSER=CBSUPER
      - JANS_COUCHBASE_SUPERUSER_PASSWORD_FILE="/etc/gluu/conf/couchbase_superuser_password"
      - JANS_COUCHBASE_CERT_FILE="/etc/certs/couchbase.crt"
      - JANS_COUCHBASE_PASSWORD_FILE="/etc/gluu/conf/couchbase_password"
      - JANS_CLIENT_API_APPLICATION_CERT_CN="client-api"
      - JANS_CLIENT_API_ADMIN_CERT_CN="client-api"
  - name: config-generate-params
    files:
      - generate.json
