# License terms and conditions for Gluu Cloud Native Edition:
# https://www.apache.org/licenses/LICENSE-2.0
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: configuration-manager-load
resources:
  - jobs.yaml
  - roles.yaml
generatorOptions:
  disableNameSuffixHash: true
images:
  - name: janssenproject/configuration-manager
    newTag: 5.0.0_dev
configMapGenerator:
  - name: gluu-config-cm
    literals:
      - CLOUD_NATIVE_CLIENT_API_SERVER_URL="client-api:8443"
      - CLOUD_NATIVE_CLIENT_API_BIND_IP_ADDRESSES="*"
      - CLOUD_NATIVE_KEY_ROTATION_FORCE="false"
      - CLOUD_NATIVE_SSL_CERT_FROM_SECRETS="true"
      - CLOUD_NATIVE_KEY_ROTATION_CHECK="3600"
      - CLOUD_NATIVE_KEY_ROTATION_INTERVAL="48"
      - CLOUD_NATIVE_LDAP_INIT="true"
      - CLOUD_NATIVE_LDAP_INIT_HOST="opendj"
      - CLOUD_NATIVE_LDAP_INIT_PORT="1636"
      - CLOUD_NATIVE_OXTRUST_CONFIG_GENERATION="true"
      - CLOUD_NATIVE_REDIS_TYPE="STANDALONE"
      - CLOUD_NATIVE_REDIS_URL="redis:6379"
      - CLOUD_NATIVE_CERT_ALT_NAME="opendj"
      #- CLOUD_NATIVE_CACHE_TYPE="REDIS"
      #-  CLOUD_NATIVE_REDIS_URL="redis:6379"
      #-  CLOUD_NATIVE_REDIS_TYPE="STANDALONE
      - CLOUD_NATIVE_MAX_RAM_PERCENTAGE="75.0"
      - CLOUD_NATIVE_SYNC_CASA_MANIFESTS="false"
      - CLOUD_NATIVE_OXTRUST_BACKEND="oxtrust:8080"
      - CLOUD_NATIVE_JACKRABBIT_SYNC_INTERVAL=300
      - CLOUD_NATIVE_JACKRABBIT_URL="http://jackrabbit:8080"
      - CLOUD_NATIVE_CONTAINER_METADATA="kubernetes"
      - CLOUD_NATIVE_SYNC_SHIB_MANIFESTS=false
      - CLOUD_NATIVE_DOCUMENT_STORE_TYPE="JCA"
      - CLOUD_NATIVE_JACKRABBIT_ADMIN_ID="admin"
      - CLOUD_NATIVE_JACKRABBIT_ADMIN_PASSWORD_FILE="/etc/gluu/conf/jackrabbit_admin_password"
      - CLOUD_NATIVE_CACHE_TYPE=GLUUCACHETYPE
      - CLOUD_NATIVE_OXTRUST_API_ENABLED=GLUUOXTRUSTAPIENABLED
      - CLOUD_NATIVE_OXTRUST_API_TEST_MODE=GLUUOXTRUSTAPITESTMODE
      - CLOUD_NATIVE_CASA_ENABLED=GLUUCASAENABBLED
      - CLOUD_NATIVE_PASSPORT_ENABLED=GLUUPASSPORTENABLED
      - CLOUD_NATIVE_RADIUS_ENABLED=GLUURADIUSENABLED
      - CLOUD_NATIVE_SAML_ENABLED=GLUUSAMLENABLED
      - CLOUD_NATIVE_CONFIG_KUBERNETES_NAMESPACE="default"
      - CLOUD_NATIVE_SECRET_KUBERNETES_NAMESPACE="default"
      - LB_ADDR=LBADDR
      - CLOUD_NATIVE_CONFIG_ADAPTER="kubernetes"
      - CLOUD_NATIVE_SECRET_ADAPTER="kubernetes"
      - DOMAIN=FQDN
      - CLOUD_NATIVE_AUTH_SERVER_BACKEND="auth-server:8080"
      # options: ldap/couchbase/hybrid
      - CLOUD_NATIVE_PERSISTENCE_TYPE=PERSISTENCETYPE
      # options: default/user/site/cache/statistic; used only if CLOUD_NATIVE_PERSISTENCE_TYPE is hybrid
      - CLOUD_NATIVE_PERSISTENCE_LDAP_MAPPING=LDAPMAPPING
      # used only if CLOUD_NATIVE_PERSISTENCE_TYPE is ldap or hybrid
      - CLOUD_NATIVE_LDAP_URL="opendj:1636"
      # used only if CLOUD_NATIVE_PERSISTENCE_TYPE is couchbase or hybrid
      - CLOUD_NATIVE_COUCHBASE_URL=COUCHBASEURL
      - CLOUD_NATIVE_COUCHBASE_USER=CBUSER
      - CLOUD_NATIVE_COUCHBASE_SUPERUSER=CBSUPER
      - CLOUD_NATIVE_COUCHBASE_SUPERUSER_PASSWORD_FILE="/etc/gluu/conf/couchbase_superuser_password"
      - CLOUD_NATIVE_COUCHBASE_CERT_FILE="/etc/certs/couchbase.crt"
      - CLOUD_NATIVE_COUCHBASE_PASSWORD_FILE="/etc/gluu/conf/couchbase_password"
      - CLOUD_NATIVE_CLIENT_API_APPLICATION_CERT_CN="client-api"
      - CLOUD_NATIVE_CLIENT_API_ADMIN_CERT_CN="client-api"
  - name: config-generate-params
    files:
      - generate.json
