apiVersion: couchbase.com/v2
kind: CouchbaseBucket
metadata:
  name: jans
  labels:
    cluster: cbjans
spec:
  name: jans #DO NOT CHANGE THIS LINE
  memoryQuota: 100Mi
  replicas: 1
  ioPriority: low
  evictionPolicy: valueOnly
  conflictResolution: seqno
  enableFlush: true
  enableIndexReplica: false
  compressionMode: passive
---
apiVersion: couchbase.com/v2
kind: CouchbaseBucket
metadata:
  name: jans-site
  labels:
    cluster: cbjans
spec:
  name: jans_site  #DO NOT CHANGE THIS LINE
  memoryQuota: 100Mi
  replicas: 1
  ioPriority: low
  evictionPolicy: valueOnly
  conflictResolution: seqno
  enableFlush: true
  enableIndexReplica: false
  compressionMode: passive
---
apiVersion: couchbase.com/v2
kind: CouchbaseBucket
metadata:
  name: jans-user
  labels:
    cluster: cbjans
spec:
  name: jans_user  #DO NOT CHANGE THIS LINE
  memoryQuota: 100Mi
  replicas: 1
  ioPriority: high
  evictionPolicy: valueOnly
  conflictResolution: seqno
  enableFlush: true
  enableIndexReplica: false
  compressionMode: passive
