kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: efs-provisioner
  namespace: default
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    spec:
      serviceAccount: efs-provisioner
      containers:
        - name: efs-provisioner
          image: quay.io/external_storage/efs-provisioner:latest
          env:
            - name: FILE_SYSTEM_ID
              value: FILESYSTEMID
            - name: AWS_REGION
              value: AWSREGION
            - name: DNS_NAME
              value: ""
            - name: PROVISIONER_NAME
              value: gluu-efs
          volumeMounts:
            - name: gluu-volume
              mountPath: /persistentvolumes
      volumes:
        - name: gluu-volume
          nfs:
            server: EFSDNSNAME
            path: /