kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
commonLabels:
  app: efs-provisioner
images:
  - name: quay.io/external_storage/efs-provisioner
    newTag: "latest"
resources:
  - deployments.yaml
  - roles.yaml
  - serviceaccounts.yaml
  - storageclasses.yaml
  - persistentvolumeclaims.yaml