kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: radius-logs-volume-claim
spec:
  storageClassName: ""
  volumeName: radius-logs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10M
  selector:
    matchLabels:
      radius: logs

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: radius-logs
  labels:
      radius: logs
spec:
  capacity:
    storage: 10M
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/radius/logs"

