# License terms and conditions for Gluu Cloud Native Edition:
# https://www.apache.org/licenses/LICENSE-2.0
image:
  repository: gluufederation/oxauth
  tag: 4.2.3_01
  pullPolicy: Always

replicas: 1
#Resources for the deployment
requests:
  memory: 1000Mi
limits:
  memory: 1536Mi

livenessProbe:
  exec:
    command:
      - python3
      - /app/scripts/healthcheck.py
  initialDelaySeconds: 30
  periodSeconds: 30
  timeoutSeconds: 5
readinessProbe:
  exec:
    command:
      - python3
      - /app/scripts/healthcheck.py
  initialDelaySeconds: 25
  periodSeconds: 25
  timeoutSeconds: 5

# service
service:
  oxAuthServiceName: oxauth
  name: http-oxauth
  port: 8080
dnsPolicy: ""
dnsConfig: {}
  # options:
  #   - name: ndots
  #     value: "5"