apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ include "cn-upgrade.fullname" . }}
    namespace: {{ .Release.Namespace }}
data:
  DOMAIN: {{ .Values.domain }}
  CN_CACHE_TYPE: {{ .Values.cnCacheType }}
  CN_CONFIG_ADAPTER: {{ .Values.configAdapterName }}
  CN_CONFIG_KUBERNETES_NAMESPACE: {{ .Release.Namespace }}
  CN_SECRET_KUBERNETES_NAMESPACE: {{ .Release.Namespace }}
  CN_SECRET_ADAPTER: {{ .Values.configSecretAdapter }}

    # options: ldap/couchbase/hybrid
  CN_PERSISTENCE_TYPE: {{ .Values.cnPersistenceType }}
    # options: default/user/site/cache/statistic; used only if CN_PERSISTENCE_TYPE is hybrid
  {{- if or (eq .Values.cnPersistenceType "hybrid") (eq .Values.cnPersistenceType "ldap") }}
  CN_PERSISTENCE_LDAP_MAPPING: {{ .Values.cnPersistenceLdapMapping | quote }}
  {{- end }}
  {{- if or (eq .Values.cnPersistenceType "ldap") (eq .Values.cnPersistenceType "hybrid")  }}
  # used only if CN_PERSISTENCE_TYPE is ldap or hybrid
  CN_LDAP_URL: {{ .Values.cnLdapUrl | quote }}
  {{- else if or (eq .Values.cnPersistenceType "couchbase") (eq .Values.cnPersistenceType "hybrid") }}
  #  used only if CN_PERSISTENCE_TYPE is couchbase or hybrid
  CN_COUCHBASE_URL: {{ .Values.cnCouchbaseUrl }}
  CN_COUCHBASE_USER: {{ .Values.cnCouchbaseUser }}
  CN_COUCHBASE_CERT_FILE: {{ .Values.cnCouchbaseCertFile | quote }}
  CN_COUCHBASE_PASSWORD_FILE: {{ .Values.cnCouchbasePassFile | quote }}
  CN_COUCHBASE_SUPERUSER: {{ .Values.cnCouchbaseSuperUser }}
  CN_COUCHBASE_SUPERUSER_PASSWORD_FILE: {{ .Values.cnCouchbaseSuperUserPassFile | quote }}
  {{- end }}
  