# License terms and conditions for Gluu Cloud Native Edition:
# https://www.apache.org/licenses/LICENSE-2.0
apiVersion: v2
appVersion: "4.2.0_dev"
home: https://www.gluu.org
maintainers:
- name: Gluu
email: support@gluu.org
description: A Helm chart for Gluu IDP
name: gluu
version: 1.0.4
dependencies:
    - name: config
      condition: global.config.enabled
      version: 1.0.4

    - name: opendj
      condition: global.opendj.enabled
      version: 1.0.4

    - name: jackrabbit
      condition: global.jackrabbit.enabled
      version: 1.0.4

    - name: oxauth
      condition: global.oxauth.enabled
      version: 1.0.4

    - name: oxtrust
      condition: global.oxtrust.enabled
      version: 1.0.4
  
    - name: nginx
      condition: global.nginx.enabled
      version: 1.0.4
  
    - name: oxshibboleth
      condition: global.oxshibboleth.enabled
      version: 1.0.4
  
    - name: oxpassport
      version: 1.0.4
      condition: persistence.configmap.gluuPassportEnabled

    - name: casa
      version: 1.0.4
      condition: persistence.configmap.gluuCasaEnabled
  
    - name: key-rotation
      condition: global.key-rotation.enabled
      version: 1.0.4
  
    - name: cr-rotate
      version: 1.0.4
      condition: global.cr-rotate.enabled
  
    - name: radius
      condition: persistence.configmap.gluuRadiusEnabled
      version: 1.0.4

    - name: oxd-server
      condition: global.oxd-server.enabled
      version: 1.0.4
  
    - name: persistence
      condition: global.persistence.enabled
      version: 1.0.4
