apiVersion: v1
entries:
  gluu:
  - annotations:
      artifacthub.io/changes: |
        - Gluu 5.0 Openbanking Distribution
        - https://gluu.org/docs/openbanking
      artifacthub.io/containsSecurityUpdates: "true"
      artifacthub.io/images: |
        - name: auth-server
          image: janssenproject/auth-server:1.0.0_b1
        - name: auth-server-key-rotation
          image: janssenproject/certmanager:1.0.0_b1
        - name:  client-api
          image: janssenproject/client-api:1.0.0_b1
        - name: configuration-manager
          image: janssenproject/configuration-manager:1.0.0_b1
        - name:  config-api
          image: janssenproject/config-api:1.0.0_b1
        - name: fido2
          image: janssenproject/fido2:1.0.0_b1
        - name: opendj
          image: janssenproject/opendj:5.0.0_dev
        - name: persistence
          image: janssenproject/persistence-loader:1.0.0_b1
        - name: scim
          image: janssenproject/scim:1.0.0_b1
      artifacthub.io/license: Apache-2.0
      artifacthub.io/prerelease: "true"
    apiVersion: v2
    appVersion: 5.0.0
    created: "2021-04-16T08:23:54.5611105-04:00"
    dependencies:
    - condition: global.config.enabled
      name: config
      repository: ""
      version: 5.0.0
    - condition: global.config-api.enabled
      name: config-api
      repository: ""
      version: 5.0.0
    - condition: global.opendj.enabled
      name: opendj
      repository: ""
      version: 5.0.0
    - condition: global.jackrabbit.enabled
      name: jackrabbit
      repository: ""
      version: 5.0.0
    - condition: global.auth-server.enabled
      name: auth-server
      repository: ""
      version: 5.0.0
    - condition: global.fido2.enabled
      name: fido2
      repository: ""
      version: 5.0.0
    - condition: global.scim.enabled
      name: scim
      repository: ""
      version: 5.0.0
    - condition: global.nginx-ingress.enabled
      name: nginx-ingress
      repository: ""
      version: 5.0.0
    - condition: global.oxshibboleth.enabled
      name: oxshibboleth
      repository: ""
      version: 5.0.0
    - condition: config.configmap.cnPassportEnabled
      name: oxpassport
      repository: ""
      version: 5.0.0
    - condition: config.configmap.cnCasaEnabled
      name: casa
      repository: ""
      version: 5.0.0
    - condition: global.auth-server-key-rotation.enabled
      name: auth-server-key-rotation
      repository: ""
      version: 5.0.0
    - condition: global.cr-rotate.enabled
      name: cr-rotate
      repository: ""
      version: 5.0.0
    - condition: config.configmap.cnRadiusEnabled
      name: radius
      repository: ""
      version: 5.0.0
    - condition: global.client-api.enabled
      name: client-api
      repository: ""
      version: 5.0.0
    - condition: global.persistence.enabled
      name: persistence
      repository: ""
      version: 5.0.0
    - condition: global.istio.ingress
      name: cn-istio-ingress
      repository: ""
      version: 5.0.0
    description: Gluu Access and Identity Mangement OpenBanking distribution
    digest: a36cd1ed68204dba6f726c057f94dcd80c613353d49bfdfbe05be1c1fc091a6a
    home: https://www.gluu.org
    icon: https://www.gluu.org/wp-content/uploads/2020/01/Gluu-Green-Icon-64.png
    kubeVersion: '>=v1.17.0-0'
    maintainers:
    - email: mo@gluu.org
      name: moabu
    name: gluu
    sources:
    - https://github.com/GluuFederation/cloud-native-edition
    urls:
    - gluu-5.0.0.tgz
    version: 5.0.0
generated: "2021-04-16T08:23:54.5521566-04:00"
