global:
  istio:
    ingress: false
    enabled: false
    namespace: istio-system
  alb:
    ingress: false
  cloud:
    testEnviroment: false
  upgrade:
    enabled: false
  provisioner: k8s.io/minikube-hostpath
  pool: default
  fsType: ext4
  gcePdStorageType: pd-standard
  azureStorageAccountType: Standard_LRS
  azureStorageKind: Managed
  reclaimPolicy: Retain
  lbIp: ""
  domain: demoexample.gluu.org
  isDomainRegistered: "false"
  gluuPersistenceType: couchbase
  gluuJackrabbitCluster: "true"
  auth-server:
    enabled: true
  fido2:
    enabled: false
  scim:
    enabled: false
  config:
    enabled: true
  jackrabbit:
    enabled: true
  persistence:
    enabled: true
  oxtrust:
    enabled: true
  opendj:
    enabled: true
  oxshibboleth:
    enabled: false
  client-api:
    enabled: false
  nginx-ingress:
    enabled: true
  auth-server-key-rotation:
    enabled: false
  cr-rotate:
    enabled: false
config:
  orgName: Gluu
  email: support@gluu.com
  adminPass: P@ssw0rd
  ldapPass: P@ssw0rd
  redisPass: P@assw0rd
  countryCode: US
  state: TX
  city: Austin
  configmap:
    jansClientApiApplicationCertCn: client-api
    jansClientApiAdminCertCn: client-api
    gluuCouchbaseCrt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURlakNDQW1LZ0F3SUJBZ0lKQUwyem5UWlREUHFNTUEwR0NTcUdTSWIzRFFFQkN3VUFNQzB4S3pBcEJnTlYKQkFNTUlpb3VZMkpuYkhWMUxtUmxabUYxYkhRdWMzWmpMbU5zZFhOMFpYSXViRzlqWVd3d0hoY05NakF3TWpBMQpNRGt4T1RVeFdoY05NekF3TWpBeU1Ea3hPVFV4V2pBdE1Tc3dLUVlEVlFRRERDSXFMbU5pWjJ4MWRTNWtaV1poCmRXeDBMbk4yWXk1amJIVnpkR1Z5TG14dlkyRnNNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUIKQ2dLQ0FRRUFycmQ5T3lvSnRsVzhnNW5nWlJtL2FKWjJ2eUtubGU3dVFIUEw4Q2RJa1RNdjB0eHZhR1B5UkNQQgo3RE00RTFkLzhMaU5takdZZk41QjZjWjlRUmNCaG1VNmFyUDRKZUZ3c0x0cTFGT3MxaDlmWGo3d3NzcTYrYmlkCjV6Umw3UEE0YmdvOXVkUVRzU1UrWDJUUVRDc0dxVVVPWExrZ3NCMjI0RDNsdkFCbmZOeHcvYnFQa2ZCQTFxVzYKVXpxellMdHN6WE5GY0dQMFhtU3c4WjJuaFhhUGlva2pPT2dyMkMrbVFZK0htQ2xGUWRpd2g2ZjBYR0V0STMrKwoyMStTejdXRkF6RlFBVUp2MHIvZnk4TDRXZzh1YysvalgwTGQrc2NoQTlNQjh3YmJORUp2ZjNMOGZ5QjZ0cTd2CjF4b0FnL0g0S1dJaHdqSEN0dFVnWU1oU0xWV3UrUUlEQVFBQm80R2NNSUdaTUIwR0ExVWREZ1FXQkJTWmQxWU0KVGNIRVZjSENNUmp6ejczZitEVmxxREJkQmdOVkhTTUVWakJVZ0JTWmQxWU1UY0hFVmNIQ01Sanp6NzNmK0RWbApxS0V4cEM4d0xURXJNQ2tHQTFVRUF3d2lLaTVqWW1kc2RYVXVaR1ZtWVhWc2RDNXpkbU11WTJ4MWMzUmxjaTVzCmIyTmhiSUlKQUwyem5UWlREUHFNTUF3R0ExVWRFd1FGTUFNQkFmOHdDd1lEVlIwUEJBUURBZ0VHTUEwR0NTcUcKU0liM0RRRUJDd1VBQTRJQkFRQk9meTVWSHlKZCtWUTBXaUQ1aSs2cmhidGNpSmtFN0YwWVVVZnJ6UFN2YWVFWQp2NElVWStWOC9UNnE4Mk9vVWU1eCtvS2dzbFBsL01nZEg2SW9CRnVtaUFqek14RTdUYUhHcXJ5dk13Qk5IKzB5CnhadG9mSnFXQzhGeUlwTVFHTEs0RVBGd3VHRlJnazZMRGR2ZEN5NVdxWW1MQWdBZVh5VWNaNnlHYkdMTjRPUDUKZTFiaEFiLzRXWXRxRHVydFJrWjNEejlZcis4VWNCVTRLT005OHBZN05aaXFmKzlCZVkvOEhZaVQ2Q0RRWWgyTgoyK0VWRFBHcFE4UkVsRThhN1ZLL29MemlOaXFyRjllNDV1OU1KdjM1ZktmNUJjK2FKdWduTGcwaUZUYmNaT1prCkpuYkUvUENIUDZFWmxLaEFiZUdnendtS1dDbTZTL3g0TklRK2JtMmoKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    gluuCouchbasePass: P@ssw0rd
    gluuCouchbaseSuperUserPass: P@ssw0rd
    gluuCouchbaseSuperUser: admin
    gluuCouchbaseUrl: cbgluu.default.svc.cluster.local
    gluuCouchbaseUser: gluu
    gluuCouchbasePassFile: /etc/gluu/conf/couchbase_password
    gluuCouchbaseSuperUserPassFile: /etc/gluu/conf/couchbase_superuser_password
    gluuCouchbaseCertFile: /etc/certs/couchbase.crt
    gluuPersistenceLdapMapping: default
    gluuCacheType: NATIVE_PERSISTENCE
    gluuSyncShibManifests: false
    gluuSyncCasaManifests: false
    gluuMaxRamPercent: "75.0"
    configAdapterName: kubernetes
    containerMetadataName: kubernetes
    configSecretAdapter: kubernetes
    gluuRedisUrl: redis:6379
    gluuRedisUseSsl: "false"
    gluuRedisType: STANDALONE
    gluuRedisSslTruststore: ""
    gluuRedisSentinelGroup: ""
    gluuOxtrustBackend: oxtrust:8080
    gluuAuthServerBackend: auth-server:8080
    jansClientApiServerUrl: client-api:8443
    jansClientApiBindIpAddresses: "*"
    gluuLdapUrl: opendj:1636
    gluuJackrabbitPostgresUser: jackrabbit
    gluuJackrabbitPostgresPasswordFile: /etc/gluu/conf/postgres_password
    gluuJackrabbitPostgresDatabaseName: jackrabbit
    gluuJackrabbitPostgresHost: postgres.postgres.svc.cluster.local
    gluuJackrabbitPostgresPort: 5432
    gluuJackrabbitAdminId: admin
    gluuJackrabbitAdminPassFile: /etc/gluu/conf/jackrabbit_admin_password
    gluuJackrabbitSyncInterval: 300
    gluuJackrabbitUrl: http://jackrabbit:8080
    gluuJackrabbitAdminIdFile: /etc/gluu/conf/jackrabbit_admin_id
    gluuDocumentStoreType: JCA
    lbAddr: ""
    ldapServiceName: opendj
    gluuOxtrustApiEnabled: false
    gluuOxtrustApiTestMode: false
    gluuPassportEnabled: false
    gluuCasaEnabled: false
    gluuRadiusEnabled: false
    gluuSamlEnabled: false
  image:
    repository: janssenproject/configuration-manager
    tag: 5.0.0_dev
  resources: {}
nginx-ingress:
  ingress:
    enabled: true
    path: /
    hosts:
    - demoexample.gluu.org
    tls:
    - secretName: tls-certificate # DON'T change
      hosts:
      - demoexample.gluu.org

jackrabbit:
  service:
    jackRabbitServiceName: jackrabbit
  replicas: 1
  secrets:
    gluuJackrabbitAdminPass: admin
    gluuJackrabbitPostgresPass: P@ssw0rd
  storage:
    size: 5Gi
  image:
    repository: gluufederation/jackrabbit
    tag: 5.0.0_dev
    pullPolicy: Always
  resources:
    limits:
      cpu: 1500m
      memory: 1000Mi
    requests:
      cpu: 1500m
      memory: 1000Mi
opendj:
  service:
    ldapServiceName: opendj
  replicas: 1
  persistence:
    size: 5Gi
  image:
    repository: gluufederation/opendj
    tag: 5.0.0_dev
    pullPolicy: Always
  resources:
    limits:
      cpu: 1500m
      memory: 2000Mi
    requests:
      cpu: 1500m
      memory: 2000Mi
persistence:
  image:
    repository: janssenproject/persistence-loader
    tag: 5.0.0_dev
    pullPolicy: Always
  resources: {}
auth-server:
  service:
    authServerServiceName: auth-server
  replicas: 1
  image:
    repository: janssenproject/auth-server
    tag: 5.0.0_dev
    pullPolicy: Always
  resources:
    limits:
      cpu: 2500m
      memory: 2500Mi
    requests:
      cpu: 2500m
      memory: 2500Mi
oxtrust:
  service:
    oxTrustServiceName: oxtrust
  replicas: 1
  image:
    repository: gluufederation/oxtrust
    tag: 5.0.0_dev
    pullPolicy: Always
  resources:
    limits:
      cpu: 1000m
      memory: 1000Mi
    requests:
      cpu: 1000m
      memory: 1000Mi
fido2:
  service:
    fido2ServiceName: fido2
  replicas: 1
  image:
    repository: janssenproject/fido2
    tag: 5.0.0_dev
    pullPolicy: Always
  resources:
    limits:
      cpu: 500m
      memory: 500Mi
    requests:
      cpu: 500m
      memory: 500Mi
scim:
  service:
    scimServiceName: scim
  image:
    repository: janssenproject/scim
    tag: 5.0.0_dev
    pullPolicy: Always
  resources:
    limits:
      cpu: 1000m
      memory: 1000Mi
    requests:
      cpu: 1000m
      memory: 1000Mi
client-api:
  service:
    clientApiServerServiceName: client-api
  replicas: 1
  image:
    repository: janssenproject/client-api
    tag: 5.0.0_dev
    pullPolicy: Always
  resources:
    limits:
      cpu: 1000m
      memory: 400Mi
    requests:
      cpu: 1000m
      memory: 400Mi
casa:
  service:
    casaServiceName: casa
  replicas: 1
  image:
    repository: gluufederation/casa
    tag: 5.0.0_dev
    pullPolicy: Always
  resources:
    requests:
      memory: "500Mi"
      cpu: "500m"
    limits:
      memory: "500Mi"
      cpu: "500m"
oxpassport:
  service:
    oxPassportServiceName: oxpassport
  replicas: 1
  image:
    repository: gluufederation/oxpassport
    tag: 5.0.0_dev
    pullPolicy: Always
  resources:
    limits:
      cpu: 700m
      memory: 900Mi
    requests:
      cpu: 700m
      memory: 900Mi
oxshibboleth:
  service:
    oxShibbolethServiceName: oxshibboleth
  replicas: 1
  image:
    repository: gluufederation/oxshibboleth
    tag: 5.0.0_dev
    pullPolicy: Always
  resources:
    limits:
      cpu: 1000m
      memory: 1000Mi
    requests:
      cpu: 1000m
      memory: 1000Mi
radius:
  service:
    radiusServiceName: radius
  replicas: 1
  image:
    repository: gluufederation/radius
    tag: 5.0.0_dev
    pullPolicy: Always
  resources:
    limits:
      cpu: 700m
      memory: 700Mi
    requests:
      cpu: 700m
      memory: 700Mi
cr-rotate:
  service:
    crRotateServiceName: cr-rotate
  image:
    repository: gluufederation/cr-rotate
    tag: 5.0.0_dev
    pullPolicy: Always
  resources:
    limits:
      cpu: 200m
      memory: 200Mi
    requests:
      cpu: 200m
      memory: 200Mi
auth-server-key-rotation:
  keysLife: 48
  image:
    repository: janssenproject/certmanager
    tag: 5.0.0_dev
    pullPolicy: Always
  resources:
    limits:
      cpu: 300m
      memory: 300Mi
    requests:
      cpu: 300m
      memory: 300Mi
