apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: oxtrust
  labels:
    APP_NAME: oxtrust
spec:
  serviceName: oxtrust
  replicas: 1
  selector:
    matchLabels:
      app: oxtrust
  template:
    spec:
      containers:
      - name: oxtrust
        imagePullPolicy: Always
        image: gluufederation/oxtrust:4.0.0_dev
        command:
          - /bin/sh
          - -c
          - |
              /usr/bin/python /scripts/update-lb-ip.py &
              /app/scripts/entrypoint.sh
        volumeMounts:
          - mountPath: /scripts
            name: update-lb-ip
      volumes:
      - name: update-lb-ip
        configMap:
          name: updatelbip