# License terms and conditions for Gluu Cloud Native Edition:
# https://www.apache.org/licenses/LICENSE-2.0
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "gluu-gateway-ui.fullname" . }}-cm
  namespace: {{ .Release.Namespace }}
data:
  DB_USER: {{ .Values.dbUser | quote }}
  DB_ADAPTER: {{ .Values.dbAdapter | quote }}
  KONG_ADMIN_URL: {{ .Values.kongAdminUrl | quote }}
  DB_HOST: {{ .Release.dbHost | quote }}
  DB_SSL: {{ .Release.dbSsl | quote }}
  DB_PORT: {{ .Values.dbPort | quote }}
  POSTGRES_VERSION: {{ .Values.postgresVersion | quote }}
  SSL_KEY_PATH: {{ .Values.sslKeyPath | quote }}
  SSL_CERT_PATH: {{ .Values.sslCertPath | quote }}
  DB_DATABASE: {{ .Values.dbDatabase }}
  NODE_ENV: {{ .Values.nodeEnv | quote }}
  PORT: {{ .Values.port }}
  OXD_SERVER_URL: {{ .Values.oxdServerUrl | quote }}
  OP_SERVER_URL: {{ .Values.opServerUrl | quote }}
  OXD_ID: {{ .Values.oxdId | quote }}
  CLIENT_ID: {{ .Values.clientId | quote }}
  CLIENT_SECRET: {{ .Values.clientSecret }}
  OXD_SERVER_VERSION: {{ .Values.oxdServerVersion }}
  GG_HOST: {{ .Values.ggHost | quote }}
  GG_UI_REDIRECT_URL_HOST: {{ .Values.ggUiRedirectUrlHost | quote }}
  EXPLICIT_HOST: {{ .Values.explicitHost | quote }}
  GG_VERSION: {{ .Values.ggVersion | quote }}
