apiVersion: v1
kind: PersistentVolume
metadata:
  name: oxtrust-pv
  labels:
      oxtrust: main
spec:
  capacity:
    storage: STORAGEOXTRUST
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: OXTRUSTVOLUMEID
    fsType: ext4