# License terms and conditions for Gluu Cloud Native Edition:
# https://www.apache.org/licenses/LICENSE-2.0
# Default values for radius.
#HorizontalPodAutoscaler
hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
  # metrics if targetCPUUtilizationPercentage is not set
  metrics: []
  #Scaling Policies
  behavior: {}

usrEnvs: {}
#  normal:
#    variable1: value1
#  secret:
#    variable4: value4

replicas: 1

image:
  repository: gluufederation/radius
  tag: 4.3.0_b1
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  radiusServiceName: radius
  ports:  
    tcp-radius-authentication:
      port: 1812
    tcp-radius-accounting:
      port: 1813
    http-jetty-service:
      port: 8080

livenessProbe:
  exec:
    command:
    - cat
    - /tmp/gluu-radius-health
  initialDelaySeconds: 30
  periodSeconds: 30
  timeoutSeconds: 5
  failureThreshold: 20
readinessProbe:
  exec:
    command:
    - cat
    - /tmp/gluu-radius-health
  initialDelaySeconds: 25
  periodSeconds: 25
  timeoutSeconds: 5
  failureThreshold: 20
# -- Resource specs.
resources:
  limits:
    # -- CPU limit.
    cpu: 700m
    # -- Memory limit.
    memory: 700Mi
  requests:
    # -- CPU request.
    cpu: 700m
    # -- Memory request.
    memory: 700Mi

nodeSelector: {}

tolerations: []

affinity: {}
volumes: []
  # Configure any additional volumes need to be attached to the pod
  # - name: mycustomcert
  #   secret:
  #     secretName: mycustomsecret
volumeMounts: []
  # Configure any additional volumesMounts that need to be attached to the containers
  # - name: mycustomcert
  #   mountPath: /etc/certs
dnsPolicy: ""
dnsConfig: {}
  # options:
  #   - name: ndots
  #     value: "5"
