# License terms and conditions for Gluu Cloud Native Edition:
# https://www.apache.org/licenses/LICENSE-2.0
# jackrabbit Environament Variables
nameOverride: ""
fullnameOverride: ""
service:
  jackRabbitServiceName: jackrabbit
  name: http-jackrabbit
  port: 8080
# StatefulSet
# values declaration
replicas: 1

secrets:
  gluuJackrabbitAdminPass: admin
  gluuJackrabbitPostgresPass: P@ssw0rd

image:
  repository: gluufederation/jackrabbit
  tag: 4.3.0_01
  pullPolicy: IfNotPresent
  
storage:
  size: 5Gi
  accessModes: ReadWriteOnce
  type: DirectoryOrCreate

livenessProbe:
  tcpSocket:
    port: http-jackrabbit
  initialDelaySeconds: 25
  periodSeconds: 25
  timeoutSeconds: 5
readinessProbe:
  tcpSocket:
    port: http-jackrabbit
  initialDelaySeconds: 30
  periodSeconds: 30
  timeoutSeconds: 5

# VolumeMounts for StatefulSet
# jackrabbit-init vm
volumeMounts:
  repository:
    mountPath: /opt/jackrabbit/repository
    name: jackrabbit-volume
  version:
    mountPath: /opt/jackrabbit/version
    name: jackrabbit-volume
  workspaces:
    mountPath: opt/jackrabbit/workspaces
    name: jackrabbit-volume
dnsPolicy: ""
dnsConfig: {}
  # options:
  #   - name: ndots
  #     value: "5"
