kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: shared-shib-pvc
spec:
  storageClassName: ""
  volumeName: shared-shib-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: STORAGESHAREDSHIB
  selector:
    matchLabels:
      type: shared-shib