# License terms and conditions for Gluu Cloud Native Edition:
# https://www.apache.org/licenses/LICENSE-2.0
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "jackrabbit.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "jackrabbit.labels" . | indent 4}}
spec:
  selector:
    matchLabels:
      app: {{ include "jackrabbit.name" . }}
  serviceName: {{ include "jackrabbit.name" . }}
  replicas: {{ .Values.replicas }} 
  template:
    metadata:
      labels:
        app: {{ include "jackrabbit.name" . }}
      {{- if .Values.global.istio.ingress }}
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
      {{- end }}
    spec:
      dnsPolicy: {{ .Values.dnsPolicy | quote }}
    {{- with .Values.dnsConfig }}
      dnsConfig:
{{ toYaml . | indent 8 }}
    {{- end }}
      volumes:
        - name: gluu-jackrabbit-admin-pass
          secret:
            secretName: gluu-jackrabbit-admin-pass
      {{- if eq .Values.global.gluuJackrabbitCluster "true" }}
        - name: gluu-jackrabbit-postgres-pass
          secret:
            secretName: gluu-jackrabbit-postgres-pass
      {{- end }}
      containers:
      - name: {{ include "jackrabbit.name" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        envFrom:
        - configMapRef:
            name: {{ .Release.Name }}-config-cm
        ports:
          - name: {{ .Values.service.name }}
            containerPort: {{ .Values.service.port }}
            protocol: TCP
        volumeMounts:
          - name: gluu-jackrabbit-admin-pass
            mountPath: /etc/gluu/conf/jackrabbit_admin_password
            subPath: jackrabbit_admin_password
        {{- if eq .Values.global.gluuJackrabbitCluster "true" }}
          - name: gluu-jackrabbit-postgres-pass
            mountPath: /etc/gluu/conf/postgres_password
            subPath: postgres_password
        {{- end }}
        {{- range $key, $values := .Values.volumeMounts }}
          - mountPath: {{$values.mountPath}}
            name: {{$values.name}}
            subPath: {{$key}}
        {{- end }}
        readinessProbe:
{{- toYaml .Values.readinessProbe | nindent 10 }}
        livenessProbe:
{{- toYaml .Values.livenessProbe | nindent 10 }}
        {{- if or (eq .Values.global.storageClass.provisioner "microk8s.io/hostpath" ) (eq .Values.global.storageClass.provisioner "k8s.io/minikube-hostpath") }}
        resources: {}
        {{- else if .Values.global.cloud.testEnviroment }}
        resources: {}
        {{- else }}
        resources:
{{- toYaml .Values.resources | nindent 10 }}
        {{- end }}
  volumeClaimTemplates:
  - metadata:
      name: jackrabbit-volume
    spec:
      accessModes:
      - {{ .Values.storage.accessModes }}
      resources:
        requests:
          storage: {{ .Values.storage.size }}
      {{- if eq .Values.global.storageClass.provisioner "k8s.io/minikube-hostpath" }}
      storageClassName: standard
      {{- else }}
      storageClassName: {{ include "jackrabbit.fullname" . | quote }}
      {{- end }}