apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cr-rotate
spec:
  selector:
    matchLabels:
      app: cr-rotate
  template:
    spec:
      containers:
      - name: cr-rotate
        imagePullPolicy: Always
        image: gluufederation/cr-rotate:4.0.0
        envFrom:
        - configMapRef:
            name: cr-rotate-cm
        volumeMounts:
          - name: cb-pass
            mountPath: "/etc/gluu/conf/couchbase_password"
            subPath: couchbase_password
          - name: cb-crt
            mountPath: "/etc/certs/couchbase.crt"
            subPath: couchbase.crt
      volumes:
      - name: cb-pass
        secret:
          secretName: cb-pass
      - name: cb-crt
        secret:
          secretName: cb-crt