# License terms and conditions for Gluu Cloud Native Edition:
# https://www.apache.org/licenses/LICENSE-2.0
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
commonLabels:
  app: oxd-server
resources:
  - services.yaml
  - deployments.yaml
images:
  - name: gluufederation/oxd-server
    newTag: 4.1.0_01
configMapGenerator:
  - name: oxd-server-cm
    literals:
      - GLUU_CONFIG_ADAPTER="kubernetes"
      - GLUU_CONFIG_KUBERNETES_NAMESPACE="default"
      - GLUU_CONFIG_KUBERNETES_CONFIGMAP="gluu"
      - GLUU_CONFIG_KUBERNETES_USE_KUBE_CONFIG="false"
      - GLUU_SECRET_ADAPTER="kubernetes"
      - GLUU_SECRET_KUBERNETES_NAMESPACE="default"
      - GLUU_SECRET_KUBERNETES_SECRET="gluu"
      - GLUU_SECRET_KUBERNETES_USE_KUBE_CONFIG="false"
      - GLUU_PERSISTENCE_TYPE="ldap"
      - GLUU_PERSISTENCE_LDAP_MAPPING="default"
      - GLUU_LDAP_URL="opendj:1636"
      - GLUU_COUCHBASE_URL="cbgluu.cbns.svc.cluster.local"
      - GLUU_COUCHBASE_USER="admin"
      - GLUU_COUCHBASE_CERT_FILE="/etc/certs/couchbase.crt"
      - GLUU_COUCHBASE_PASSWORD_FILE="/etc/gluu/conf/couchbase_password"
      - GLUU_COUCHBASE_CONN_TIMEOUT="10000"
      - GLUU_COUCHBASE_CONN_MAX_WAIT="20000"
      - GLUU_COUCHBASE_SCAN_CONSISTENCY="not_bounded"
      - APPLICATION_KEYSTORE_PATH="/opt/oxd-server/conf/oxd-server.keystore"
      - APPLICATION_KEYSTORE_CN="oxd_server"
      - APPLICATION_KEYSTORE_PASSWORD_FILE="/etc/gluu/conf/app_keystore_password"
      - ADMIN_KEYSTORE_PATH="/opt/oxd-server/conf/oxd-server.keystore"
      - ADMIN_KEYSTORE_CN="oxd_server"
      - ADMIN_KEYSTORE_PASSWORD_FILE="/etc/gluu/conf/admin_keystore_password"
      # h2 or redis
      - STORAGE="h2"
      - GLUU_SERVER_HOST=""
      - GLUU_REDIS_URL="redis:6379"
      - GLUU_REDIS_TYPE=STANDALONE
      - LB_ADDR=LBADDR