apiVersion: apps/v1
kind: Deployment
metadata:
  name: oxd-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oxd-server
  template:
    spec:
      volumes:
        - name: oxd-server
          persistentVolumeClaim:
            claimName: oxd-server-pvc
      containers:
      - name: oxd-server
        imagePullPolicy: Always
        image: gluufederation/oxd-server:4.0.0_dev
        ports:
        - containerPort: 8443
        - containerPort: 8444
        resources:
          requests:
            memory: "500Mi"
          limits:
            memory: "1536Mi"
        envFrom:
        - configMapRef:
            name: oxd-server-cm