apiVersion: v1
kind: PersistentVolume
metadata:
  name: opendj-pv
  labels:
    type: opendj
spec:
  capacity:
    storage: STORAGELDAP
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/opendj"
    type: DirectoryOrCreate