# License terms and conditions for Gluu Cloud Native Edition:
# https://www.apache.org/licenses/LICENSE-2.0
apiVersion: v1
kind: PersistentVolume
metadata:
  name: shared-shib-pv
  labels:
      app: shared-shib
spec:
  capacity:
    storage: STORAGESHAREDSHIB
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/shared-shibboleth-idp"
    type: DirectoryOrCreate