# License terms and conditions for Gluu Cloud Native Edition:
# https://www.apache.org/licenses/LICENSE-2.0
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: shared-shib-pvc
spec:
  storageClassName: ""
  volumeName: shared-shib-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: STORAGESHAREDSHIB
  selector:
    matchLabels:
      type: shared-shib