# License terms and conditions:
# https://www.gluu.org/license/enterprise-edition/
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: shared-shib-pvc
spec:
  storageClassName: ""
  volumeName: shared-shib-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: STORAGESHAREDSHIB
  selector:
    matchLabels:
      type: shared-shib