# License terms and conditions:
# https://www.gluu.org/license/enterprise-edition/
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: opendj
spec:
  volumeClaimTemplates:
    - metadata:
        name: opendj-pvc
      spec:
        storageClassName: opendj-sc
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: STORAGELDAP