# License terms and conditions:
# https://www.gluu.org/license/enterprise-edition/
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: opendj-sc
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: "false"
provisioner: kubernetes.io/aws-ebs
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
mountOptions:
- debug
parameters:
  type: VOLUMETYPE
  encrypted: "true"
allowedTopologies:
- matchLabelExpressions:
  - key: failure-domain.beta.kubernetes.io/zone
    values: