# License terms and conditions for Gluu Cloud Native Edition:
# https://www.apache.org/licenses/LICENSE-2.0
apiVersion: v1
kind: Service
metadata:
  name: {{ include "scim.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "scim.labels" . | indent 4}}
spec:
  ports:
  - port: {{ .Values.ports.containerPort }}
    name: {{ .Values.global.scimServiceName }}
  selector:
    app: {{ include "scim.name" . }} #scim
    