apiVersion: v1
kind: PersistentVolume
metadata:
  name: casa-pv
  labels:
    type: casa
spec:
  capacity:
    storage: STORAGECASA
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "HOME_DIR/casa"
    type: DirectoryOrCreate