apiVersion: v1
kind: Service
metadata:
  name: oxd-server
spec:
  ports:
  - port: 8444
    name: oxd-server-admin-gui
  - port: 8443
    name: oxd-server-app-connector
  selector:
    app: oxd-server