apiVersion: apps/v1
kind: Deployment
metadata:
  name: oxauth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oxauth
  template:
    spec:
      containers:
      - name: oxauth
        imagePullPolicy: Always
        image: gluufederation/oxauth:4.0.0
        resources:
          requests:
            memory: "1000Mi"
          limits:
            memory: "1536Mi"
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: oxauth-cm
        volumeMounts:
          - mountPath: /opt/gluu/jetty/oxauth/logs
            name: oxauth-volume
            subPath: logs
          - mountPath: /opt/gluu/jetty/oxauth/lib/ext
            name: oxauth-volume
            subPath: ext
          - mountPath: /opt/gluu/jetty/oxauth/custom/static
            name: oxauth-volume
            subPath: static
          - mountPath: /opt/gluu/jetty/oxauth/custom/pages
            name: oxauth-volume
            subPath: pages
          - name: cb-pass
            mountPath: "/etc/gluu/conf/couchbase_password"
            subPath: couchbase_password
          - name: cb-crt
            mountPath: "/etc/certs/couchbase.crt"
            subPath: couchbase.crt
          - name: casa
            mountPath: "/etc/gluu/conf/casa.json"
            subPath: casa.json
        livenessProbe:
          httpGet:
            path: /oxauth/.well-known/openid-configuration
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /oxauth/.well-known/openid-configuration
            port: 8080
          initialDelaySeconds: 25
          periodSeconds: 25
      hostAliases:
      - ip: NGINX_IP
        hostnames:
        - FQDN
      volumes:
      - name: oxauth-volume
        persistentVolumeClaim:
          claimName: oxauth-pvc
      - name: cb-pass
        secret:
          secretName: cb-pass
      - name: cb-crt
        secret:
          secretName: cb-crt
      - name: casa
        configMap:
          name: casacm