apiVersion: couchbase.com/v1
kind: CouchbaseCluster
metadata:
  name: CLUSTERNAME #DO NOT CHANGE THIS LINE
spec:
  baseImage: couchbase/server
  version: enterprise-6.0.2
  antiAffinity: false
  tls:
    static:
      member:
        serverSecret: couchbase-server-tls
      operatorSecret: couchbase-operator-tls
  authSecret: cb-auth
  exposeAdminConsole: true
  adminConsoleServices:
    - data
  exposedFeatures:
    - xdcr
    - client
  exposedFeatureServiceType: NodePort
  cluster:
    dataServiceMemoryQuota: 512
    indexServiceMemoryQuota: 256
    searchServiceMemoryQuota: 256
    eventingServiceMemoryQuota: 256
    analyticsServiceMemoryQuota: 1024
    indexStorageSetting: memory_optimized
    autoFailoverTimeout: 10
    autoFailoverMaxCount: 3
    autoFailoverOnDataDiskIssues: true
    autoFailoverOnDataDiskIssuesTimePeriod: 120
    autoFailoverServerGroup: false
  buckets:
    - name: gluu #DO NOT CHANGE THIS LINE
      type: couchbase
      memoryQuota: 100
      replicas: 1
      ioPriority: high
      evictionPolicy: valueOnly
      conflictResolution: seqno
      enableFlush: true
      enableIndexReplica: false
      compressionMode: "off"
    - name: gluu_cache #DO NOT CHANGE THIS LINE
      type: couchbase
      memoryQuota: 100
      replicas: 1
      ioPriority: high
      evictionPolicy: valueOnly
      conflictResolution: seqno
      enableFlush: true
      enableIndexReplica: false
      compressionMode: "off"
    - name: gluu_site #DO NOT CHANGE THIS LINE
      type: couchbase
      memoryQuota: 100
      replicas: 1
      ioPriority: high
      evictionPolicy: valueOnly
      conflictResolution: seqno
      enableFlush: true
      enableIndexReplica: false
      compressionMode: "off"
    - name: gluu_token #DO NOT CHANGE THIS LINE
      type: couchbase
      memoryQuota: 100
      replicas: 1
      ioPriority: high
      evictionPolicy: valueOnly
      conflictResolution: seqno
      enableFlush: true
      enableIndexReplica: false
      compressionMode: "off"
    - name: gluu_user #DO NOT CHANGE THIS LINE
      type: couchbase
      memoryQuota: 100
      replicas: 1
      ioPriority: high
      evictionPolicy: valueOnly
      conflictResolution: seqno
      enableFlush: true
      enableIndexReplica: false
      compressionMode: "off"

  servers:
    - name: allservices
      size: 1
      services:
        - data
        - index
        - query
        - search
        - eventing
        - analytics
      pod:
        volumeMounts:
          default: pvc-general
          data:  pvc-data
          index: pvc-index
          analytics:
            - pvc-analytics
    - name: allservices1
      size: 1
      services:
        - data
        - index
        - query
        - search
        - eventing
        - analytics
      pod:
        volumeMounts:
          default: pvc-general
          data:  pvc-data
          index: pvc-index
          analytics:
            - pvc-analytics
  securityContext:
    fsGroup: 1000
  volumeClaimTemplates:
    - metadata:
        name: pvc-general
      spec:
        storageClassName: couchbase-sc
        resources:
          requests:
            storage: 5Gi
    - metadata:
        name: pvc-data
      spec:
        storageClassName: couchbase-sc
        resources:
          requests:
            storage: 5Gi
    - metadata:
        name: pvc-index
      spec:
        storageClassName: couchbase-sc
        resources:
          requests:
            storage: 5Gi
    - metadata:
        name: pvc-analytics
      spec:
        storageClassName: couchbase-sc
        resources:
          requests:
            storage: 5Gi