kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
bases:
  - ../../../base
resources:
  - persistentvolumeclaims.yaml
  - persistentvolumes.yaml
patchesStrategicMerge:
  - statefulsets.yaml