# License terms and conditions for Gluu Cloud Native Edition:
# https://www.apache.org/licenses/LICENSE-2.0
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: persistence-load
resources:
  - jobs.yaml
images:
  - name: janssenproject/persistence-loader
    newTag: 5.0.0_dev

