# License terms and conditions for Gluu Cloud Native Edition:
# https://www.apache.org/licenses/LICENSE-2.0
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ldap-backup.fullname" . }}
  namespace: {{ .Release.Namespace }}
data:
  CN_LDAP_AUTO_REPLICATE: {{ .Values.cnLdapAutoReplicate | quote }}
  CN_CONFIG_KUBERNETES_NAMESPACE: {{ .Release.Namespace | quote }}
  CN_SECRET_KUBERNETES_NAMESPACE: {{ .Release.Namespace | quote }}
  CN_CONFIG_ADAPTER: {{ .Values.configAdapterName | quote }}
  CN_SECRET_ADAPTER: {{ .Values.configSecretAdapter | quote }}
  CN_LDAP_INIT_HOST: {{ .Values.ldapServiceName }}
  CN_LDAP_INIT: {{ .Values.cnLdapInit | quote }} # TODO: To be removed
  CN_LDAP_INIT_PORT: {{ .Values.cnLdapInitPort | quote }}
  CN_OXTRUST_CONFIG_GENERATION: {{ .Values.gluuOxtrustConfigGeneration | quote }}
  CN_CACHE_TYPE: {{ .Values.gluuCacheType | quote }}
  {{- if and (.Values.gluuRedisEnabled) (eq .Values.gluuCacheType "REDIS") }}
  CN_REDIS_URL: {{ .Values.gluuRedisUrl | quote }}
  CN_REDIS_TYPE: {{ .Values.gluuRedisType | quote }}
  {{- end }}
  # must the same as the opendj service name
  CN_CERT_ALT_NAME: {{ .Values.ldapServiceName }}

  