# License terms and conditions for Gluu Cloud Native Edition:
# https://www.apache.org/licenses/LICENSE-2.0
# Default values for oxshibboleth.
replicas: 1

image:
  repository: gluufederation/oxshibboleth
  tag: 4.2.3_01
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

service:
  port: 8080
  targetPort: 8080
  oxShibbolethServiceName: oxshibboleth
  name: http-oxshibboleth

resources: 
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
   memory: 1000Mi # "1000Mi"
  requests:
   memory: 1000Mi # "1536Mi"

livenessProbe:
  httpGet:
    path: /idp
    port: http-oxshibboleth
  initialDelaySeconds: 30
  periodSeconds: 30
  timeoutSeconds: 5
readinessProbe:
  httpGet:
    path: /idp
    port: http-oxshibboleth
  initialDelaySeconds: 25
  periodSeconds: 25
  timeoutSeconds: 5

nodeSelector: {}

tolerations: []

affinity: {}
dnsPolicy: ""
dnsConfig: {}
  # options:
  #   - name: ndots
  #     value: "5"
