# License terms and conditions:
# https://www.gluu.org/license/enterprise-edition/
apiVersion: batch/v1
kind: Job
metadata:
  name: gluu-upgrade-job
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: gluu-upgrade-job
          image: gluufederation/upgrade:4.0.0
          envFrom:
          - configMapRef:
              name: upgrade-cm
          args: ["--source", "4.0", "--target", "4.1"]
          volumeMounts:
            - name: cb-pass
              mountPath: "/etc/gluu/conf/couchbase_password"
              subPath: couchbase_password
            - name: cb-crt
              mountPath: "/etc/certs/couchbase.crt"
              subPath: couchbase.crt
            - name: ox-ldif-cm
              mountPath: "/opt/opendj/config/schema/101-ox.ldif"
              subPath: 101-ox.ldif
      volumes:
      - name: cb-pass
        secret:
          secretName: cb-pass
      - name: cb-crt
        secret:
          secretName: cb-crt
      - name: ox-ldif-cm
        configMap:
          name: ox-ldif-cm
