# License terms and conditions for Gluu Cloud Native Edition:
# https://www.apache.org/licenses/LICENSE-2.0
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: gluu-upgrade
resources:
  - jobs.yaml
images:
  - name: gluufederation/upgrade
    newTag: 5.0.0_dev
configMapGenerator:
  - name: upgrade-cm
    literals:
      - CN_CONFIG_KUBERNETES_NAMESPACE="default"
      - CN_SECRET_KUBERNETES_NAMESPACE="default"
      - CN_CONFIG_ADAPTER="kubernetes"
      - CN_SECRET_ADAPTER="kubernetes"
      - DOMAIN=FQDN
      # options: ldap/couchbase/hybrid
      - CN_PERSISTENCE_TYPE=PERSISTENCETYPE
      # options: default/user/site/cache/statistic; used only if CN_PERSISTENCE_TYPE is hybrid
      - CN_PERSISTENCE_LDAP_MAPPING=LDAPMAPPING
      # used only if CN_PERSISTENCE_TYPE is ldap or hybrid
      - CN_LDAP_URL="opendj:1636"
      # used only if CN_PERSISTENCE_TYPE is couchbase or hybrid
      - CN_COUCHBASE_URL=COUCHBASEURL
      - CN_COUCHBASE_USER=CBUSER
      - CN_COUCHBASE_CERT_FILE="/etc/certs/couchbase.crt"
      - CN_COUCHBASE_PASSWORD_FILE="/etc/gluu/conf/couchbase_password"
      - CN_CACHE_TYPE=CNCACHETYPE
