apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs
spec:
  capacity:
    # 1Mi
    storage: STORAGENFS
  accessModes:
    - ReadWriteMany
  nfs:
    server: NFSIP
    path: "/opt/shared-shibboleth-idp"