name: release
on:
  push:
    branches:
      - "4.5"
      # below branch is triggered by jenkins which triggers dev image
      - update-source-build-date
  workflow_dispatch:
jobs:
  release-simple-pr:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Import GPG key
      id: import_gpg
      uses: crazy-max/ghaction-import-gpg@v4
      with:
        gpg_private_key: ${{ secrets.MOAUTO_GPG_PRIVATE_KEY }}
        passphrase: ${{ secrets.MOAUTO_GPG_PRIVATE_KEY_PASSPHRASE }}
        git_user_signingkey: true
        git_commit_gpgsign: true

    - name: Configure Git
      run: |
        git config user.name "mo-auto"
        git config user.email "54212639+mo-auto@users.noreply.github.com"
        git config --global user.signingkey "${{ steps.import_gpg.outputs.keyid }}"

    - uses: google-github-actions/release-please-action@v3.1
      id: release-please
      with:
         token: ${{ secrets.MOWORKFLOWTOKEN }}
         release-type: simple
