# License terms and conditions for Gluu Cloud Native Edition:
# https://www.apache.org/licenses/LICENSE-2.0
# Default values for oxauth-key-rotation.

usrEnvs: {}
#  normal:
#    variable1: value1
#  secret:
#    variable4: value4

image:
  repository: gluufederation/certmanager
  tag: 4.3.0_b1
  pullPolicy: IfNotPresent
keysLife: 48
nameOverride: ""
fullnameOverride: ""

# -- Resource specs.
resources:
  limits:
    # -- CPU limit.
    cpu: 300m
    # -- Memory limit.
    memory: 300Mi
  requests:
    # -- CPU request.
    cpu: 300m
    # -- Memory request.
    memory: 300Mi

nodeSelector: {}

tolerations: []

affinity: {}
volumes: []
  # Configure any additional volumes need to be attached to the pod
  # - name: mycustomcert
  #   secret:
  #     secretName: mycustomsecret
volumeMounts: []
  # Configure any additional volumesMounts that need to be attached to the containers
  # - name: mycustomcert
  #   mountPath: /etc/certs
dnsPolicy: ""
dnsConfig: {}
  # options:
  #   - name: ndots
  #     value: "5"
