apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-shib-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: STORAGESHAREDSHIB   
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: casa-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: STORAGECASA
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc
  labels:
    app: nfs-pvc
spec:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 50Gi