# License terms and conditions for Gluu Cloud Native Edition:
# https://www.apache.org/licenses/LICENSE-2.0
replicas: 1
image:
  repository: gluufederation/scim
  tag: 4.3.0_01
  pullPolicy: IfNotPresent

#Resources for the deployment
requests:
  memory: 1000Mi
limits:
  memory: 1000Mi

#ports for the deployment
ports:
  containerPort: 8080

# service
service:
  scimServiceName: scim
  name: http-scim
dnsPolicy: ""
dnsConfig: {}
  # options:
  #   - name: ndots
  #     value: "5"
