# License terms and conditions for Gluu Cloud Native Edition:
# https://www.apache.org/licenses/LICENSE-2.0
replicas: 1
image:
  repository: gluufederation/scim
  tag: 4.2.3_01
  pullPolicy: Always

#Resources for the deployment
requests:
  memory: 1000Mi
limits:
  memory: 1000Mi

livenessProbe:
  httpGet:
    path: /scim/restv1/scim/v2/ServiceProviderConfig
    port: 8080
  initialDelaySeconds: 30
  periodSeconds: 30
  timeoutSeconds: 5
readinessProbe:
  httpGet:
    path: /scim/restv1/scim/v2/ServiceProviderConfig
    port: 8080
  initialDelaySeconds: 25
  periodSeconds: 25
  timeoutSeconds: 5
# service
service:
  scimServiceName: scim
  name: http-scim
  port: 8080
dnsPolicy: ""
dnsConfig: {}
  # options:
  #   - name: ndots
  #     value: "5"
