apiVersion: apps/v1
kind: Deployment
metadata:
  name: oxpassport
spec:
  # serviceName: oxpassport
  replicas: 1
  selector:
    matchLabels:
      app: oxpassport
  template:
    spec:
      containers:
      - name: oxpassport
        imagePullPolicy: Always
        image: gluufederation/oxpassport:4.0.1_02
        ports:
        - containerPort: 8090
        envFrom:
        - configMapRef:
            name: oxpassport-cm
        livenessProbe:
          httpGet:
            path: /passport/token
            port: 8090
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /passport/token
            port: 8090
          initialDelaySeconds: 25
          periodSeconds: 25
        volumeMounts:
          - name: cb-pass
            mountPath: "/etc/gluu/conf/couchbase_password"
            subPath: couchbase_password
          - name: cb-crt
            mountPath: "/etc/certs/couchbase.crt"
            subPath: couchbase.crt
      volumes:
      - name: cb-pass
        secret:
          secretName: cb-pass
      - name: cb-crt
        secret:
          secretName: cb-crt
      hostAliases:
      - ip: NGINX_IP
        hostnames:
        - FQDN
