# License terms and conditions for Gluu Cloud Native Edition:
# https://www.apache.org/licenses/LICENSE-2.0
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "oxd-server.fullname" . }}
  namespace: {{ .Release.Namespace }}
data:
  GLUU_CONFIG_ADAPTER: {{ .Values.global.configAdapterName }}
  GLUU_SECRET_ADAPTER: {{ .Values.global.configSecretAdapter }}
  GLUU_CONFIG_KUBERNETES_NAMESPACE: {{ .Release.Namespace | quote }}
  GLUU_SECRET_KUBERNETES_NAMESPACE: {{ .Release.Namespace | quote }}
  GLUU_MAX_RAM_PERCENTAGE: {{ .Values.global.gluuMaxRamPercent | quote }}
  APPLICATION_KEYSTORE_CN: {{ .Values.configmap.applicationKeystoreCn | quote }}
  ADMIN_KEYSTORE_CN: {{ .Values.configmap.adminKeystoreCn | quote }}
  GLUU_SERVER_HOST: {{ .Values.global.domain | quote }}
  APPLICATION_KEYSTORE_PASSWORD_FILE: {{ .Values.configmap.applicationKeystorePasswordFile | quote }}
  ADMIN_KEYSTORE_PASSWORD_FILE: {{ .Values.configmap.adminKeystorePasswordFile | quote }}
  GLUU_REDIS_URL: {{ .Values.global.gluuRedisUrl | quote }}
  GLUU_REDIS_TYPE: {{ .Values.global.gluuRedisType | quote }}
  STORAGE: {{ .Values.configmap.storage | quote }}
  {{- if and (and .Values.global.cloud.enabled (eq .Values.global.isDomainRegistered "false") ) (eq .Values.global.provisioner "kubernetes.io/aws-ebs") }}
  LB_ADDR: {{ .Values.global.lbAddr }}
  {{- end }}
