# License terms and conditions for Gluu Cloud Native Edition:
# https://www.apache.org/licenses/LICENSE-2.0
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "oxd-server.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "oxd-server.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "oxd-server.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "oxd-server.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if and (eq .Values.global.isDomainRegistered "false") (or (eq .Values.global.provisioner "kubernetes.io/aws-ebs") (eq .Values.global.provisioner "openebs.io/local")) }}
          command:
            - /bin/sh
            - -c 
            - |
                /usr/bin/python3 /scripts/updatelbip.py &
                /app/scripts/entrypoint.sh
          {{- end }}
          ports:
            - containerPort: 8444
            - containerPort: 8443   
          envFrom:
            - configMapRef:
                name: {{ include "oxd-server.fullname" . }}
          livenessProbe:
            exec:
              command:
                - curl
                - -k
                - https://localhost:8443/health-check
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            exec:
              command:
                - curl
                - -k
                - https://localhost:8443/health-check
            initialDelaySeconds: 25
            periodSeconds: 25
          volumeMounts:
            - name: {{ include "oxd-server.name" . }}-admin-password
              mountPath: /etc/gluu/conf/admin_keystore_password
              subPath: admin_keystore_password
            - name: {{ include "oxd-server.name" . }}-app-password
              mountPath: /etc/gluu/conf/app_keystore_password
              subPath: app_keystore_password
            {{- if and (eq .Values.global.isDomainRegistered "false") (or (eq .Values.global.provisioner "kubernetes.io/aws-ebs") (eq .Values.global.provisioner "openebs.io/local")) }}
            - name: {{ include "oxd-server.name" . }}-updatelbip
              mountPath: /scripts
            {{- end }}
          {{- if or (eq .Values.global.provisioner "microk8s.io/hostpath" ) (eq .Values.global.provisioner "k8s.io/minikube-hostpath") }}
          resources: {}
          {{- else if .Values.global.cloud.testEnviroment }}
          resources: {}
          {{- else }}
          resources:
{{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
      volumes:
        - name: {{ include "oxd-server.name" . }}-admin-password
          secret:
            secretName: {{ include "oxd-server.fullname" . }}
            items:
            - key: admin_keystore_password
              path: admin_keystore_password
        - name: {{ include "oxd-server.name" . }}-app-password
          secret:
            secretName: {{ include "oxd-server.fullname" . }}
            items:
            - key: app_keystore_password
              path: app_keystore_password
        {{- if and (eq .Values.global.isDomainRegistered "false") (or (eq .Values.global.provisioner "kubernetes.io/aws-ebs") (eq .Values.global.provisioner "openebs.io/local")) }}
        - name: {{ include "oxd-server.name" . }}-updatelbip
          configMap:
            name: {{ .Release.Name }}-updatelbip
        {{- end }}
      {{- if eq .Values.global.isDomainRegistered "false" }}
      hostAliases:
      - ip: {{ .Values.global.nginxIp }}
        hostnames:
        - {{ .Values.global.domain }}
      {{- end }}

