# License terms and conditions for Gluu Cloud Native Edition:
# https://www.apache.org/licenses/LICENSE-2.0
# Default values for oxpassport.
replicas: 1

image:
  repository: gluufederation/oxpassport
  tag: 4.3.0_01
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  oxPassportServiceName: oxpassport
  port: 8090
  name: http-oxpassport

livenessProbe:
  httpGet:
    path: /passport/health-check
    port: http-passport
  initialDelaySeconds: 30
  periodSeconds: 30
  timeoutSeconds: 5
  failureThreshold: 20
readinessProbe:
  httpGet:
    path: /passport/health-check
    port: http-passport
  initialDelaySeconds: 25
  periodSeconds: 25
  timeoutSeconds: 5
  failureThreshold: 20

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
dnsPolicy: ""
dnsConfig: {}
  # options:
  #   - name: ndots
  #     value: "5"
