kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: casa-sc
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: "false"
provisioner: kubernetes.io/aws-ebs
allowVolumeExpansion: true
reclaimPolicy: Retain
mountOptions:
- debug
parameters:
  type: VOLUMETYPE
  encrypted: "true"
  zones: SCCASAZONE