# License terms and conditions:
# https://www.gluu.org/license/enterprise-edition/
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
commonLabels:
  app: couchbase-backup
resources:
  - cronjobs.yaml
  - jobs.yaml
  - persistentvolumeclaims.yaml
  - storageclasses.yaml
images:
  - name: couchbase/server
    newTag: enterprise-6.5.0
