kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: casa-pvc
spec:
  storageClassName: ""
  volumeName: casa-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: STORAGECASA
  selector:
    matchLabels:
      type: casa