version: "3.7"

networks:
  gluu:
    external: true

services:
  # the following services simulate statefulset where each service has 1 container with fixed hostname and server alias
  # due to limitation in docker networking, container is not reachable by its hostname and there's no templating support
  # in networks definition
  ldap_manager:
    image: gluufederation/wrends:4.0.1_01
    hostname: "ldap.{{.Node.Hostname}}"
    environment:
      - GLUU_CONFIG_CONSUL_HOST=consul.server
      - GLUU_CONFIG_CONSUL_CONSISTENCY=default
      - GLUU_SECRET_VAULT_HOST=vault.server
      # - GLUU_LDAP_ADVERTISE_ADDR=ldap.{{.Node.Hostname}}
      # the value must match network alias `ldap.server` because other containers
      # use this value as LDAP hostname
      - GLUU_CERT_ALT_NAME=ldap.server
    networks:
      gluu:
        aliases:
          - ldap.manager
          - ldap.server
    deploy:
      mode: global
      endpoint_mode: dnsrr
      update_config:
        parallelism: 1
        failure_action: rollback
        delay: 30s
      restart_policy:
        condition: any
        delay: 5s
        window: 120s
      placement:
        constraints:
          - node.hostname == manager
    volumes:
      - /opt/opendj/db:/opt/opendj/db
      - /opt/opendj/config:/opt/opendj/config
      - /opt/opendj/ldif:/opt/opendj/ldif
      - /opt/opendj/logs:/opt/opendj/logs
      - /opt/opendj/backup:/opt/opendj/bak
    labels:
      - "SERVICE_IGNORE=yes"
    secrets:
      - source: vault_role_id
        target: /etc/certs/vault_role_id
      - source: vault_secret_id
        target: /etc/certs/vault_secret_id

  ldap_worker_1:
    image: gluufederation/wrends:4.0.1_01
    hostname: "ldap.{{.Node.Hostname}}"
    environment:
      - GLUU_CONFIG_CONSUL_HOST=consul.server
      - GLUU_CONFIG_CONSUL_CONSISTENCY=default
      - GLUU_SECRET_VAULT_HOST=vault.server
      # - GLUU_LDAP_ADVERTISE_ADDR=ldap.{{.Node.Hostname}}
      # the value must match network alias `ldap.server` because other containers
      # use this value as LDAP hostname
      - GLUU_CERT_ALT_NAME=ldap.server
    networks:
      gluu:
        aliases:
          - ldap.worker-1
          - ldap.server
    deploy:
      mode: global
      endpoint_mode: dnsrr
      update_config:
        parallelism: 1
        failure_action: rollback
        delay: 30s
      restart_policy:
        condition: any
        delay: 5s
        window: 120s
      placement:
        constraints:
          - node.hostname == worker-1
    volumes:
      - /opt/opendj/db:/opt/opendj/db
      - /opt/opendj/config:/opt/opendj/config
      - /opt/opendj/ldif:/opt/opendj/ldif
      - /opt/opendj/logs:/opt/opendj/logs
      - /opt/opendj/backup:/opt/opendj/bak
    labels:
      - "SERVICE_IGNORE=yes"
    secrets:
      - source: vault_role_id
        target: /etc/certs/vault_role_id
      - source: vault_secret_id
        target: /etc/certs/vault_secret_id

  ldap_worker_2:
    image: gluufederation/wrends:4.0.1_01
    hostname: "ldap.{{.Node.Hostname}}"
    environment:
      - GLUU_CONFIG_CONSUL_HOST=consul.server
      - GLUU_CONFIG_CONSUL_CONSISTENCY=default
      - GLUU_SECRET_VAULT_HOST=vault.server
      # - GLUU_LDAP_ADVERTISE_ADDR=ldap.{{.Node.Hostname}}
      # the value must match network alias `ldap.server` because other containers
      # use this value as LDAP hostname
      - GLUU_CERT_ALT_NAME=ldap.server
    networks:
      gluu:
        aliases:
          - ldap.worker-2
          - ldap.server
    deploy:
      mode: global
      endpoint_mode: dnsrr
      update_config:
        parallelism: 1
        failure_action: rollback
        delay: 30s
      restart_policy:
        condition: any
        delay: 5s
        window: 120s
      placement:
        constraints:
          - node.hostname == worker-2
    volumes:
      - /opt/opendj/db:/opt/opendj/db
      - /opt/opendj/config:/opt/opendj/config
      - /opt/opendj/ldif:/opt/opendj/ldif
      - /opt/opendj/logs:/opt/opendj/logs
      - /opt/opendj/backup:/opt/opendj/bak
    labels:
      - "SERVICE_IGNORE=yes"
    secrets:
      - source: vault_role_id
        target: /etc/certs/vault_role_id
      - source: vault_secret_id
        target: /etc/certs/vault_secret_id

secrets:
  vault_role_id:
    external: true
  vault_secret_id:
    external: true
