# License terms and conditions:
# https://www.gluu.org/license/enterprise-edition/
# Default values for persistence.
replicaCount: 1

image:
  repository: gluufederation/persistence
  tag: 4.0.1_04
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

configmap:
  #support for oxtrust API
  gluuOxtrustApiEnabled: false
  gluuOxtrustApiTestMode: false
  gluuCasaEnabled: true
  gluuPassportEnabled: false
  gluuRadiusEnabled: false
  gluuSamlEnabled: true  
