apiVersion: apps/v1
kind: Deployment
metadata:
  name: radius
spec:
  replicas: 1
  selector:
    matchLabels:
      app: radius
  template:
    spec:
      containers:
      - name: radius
        imagePullPolicy: Always
        image: gluufederation/radius:4.0.1_01
        resources:
          requests:
            memory: "1000Mi"
          limits:
            memory: "1536Mi"
        ports:
        - containerPort: 8080
        - containerPort: 1812
        - containerPort: 1813
        envFrom:
        - configMapRef:
            name: radius-cm
        volumeMounts:
          - name: cb-pass
            mountPath: "/etc/gluu/conf/couchbase_password"
            subPath: couchbase_password
          - name: cb-crt
            mountPath: "/etc/certs/couchbase.crt"
            subPath: couchbase.crt            
        livenessProbe:
          exec:
            command:
            - cat
            - /tmp/gluu-radius-health
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          exec:
            command:
            - cat
            - /tmp/gluu-radius-health
          initialDelaySeconds: 25
          periodSeconds: 25
      hostAliases:
      - ip: NGINX_IP
        hostnames:
        - FQDN
      volumes:
      - name: cb-pass
        secret:
          secretName: cb-pass
      - name: cb-crt
        secret:
          secretName: cb-crt