kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: oxd-server-sc
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: "false"
provisioner: kubernetes.io/aws-ebs
allowVolumeExpansion: true
parameters:
  type: VOLUMETYPE
  encrypted: "true"
  # Example: us-west-2a
  zones: SCOXDSERVERZONE
reclaimPolicy: Retain
mountOptions:
- debug 