apiVersion: v1
kind: PersistentVolume
metadata:
  name: shared-shib
spec:
  capacity:
    storage: STORAGESHAREDSHIB
  accessModes:
    - ReadWriteMany
  nfs:
    server: NFSIP
    path: "/opt/shared-shibboleth-idp"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: casa
spec:
  capacity:
    storage: STORAGECASA
  accessModes:
    - ReadWriteMany
  nfs:
    server: NFSIP
    path: "/data/casa"