apiVersion: apps/v1
kind: Deployment
metadata:
  name: oxd-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oxd-server
  template:
    spec:
      containers:
      - name: oxd-server
        imagePullPolicy: Always
        image: gluufederation/oxd-server:4.0.1_01
        command:
          - /bin/sh
          - -c
          - |
              /usr/bin/python /scripts/update-lb-ip.py &
              /app/scripts/entrypoint.sh
        ports:
        - containerPort: 8443
        - containerPort: 8444
        resources:
          requests:
            memory: "500Mi"
          limits:
            memory: "1536Mi"
        envFrom:
        - configMapRef:
            name: oxd-server-cm
        volumeMounts:
          - mountPath: /opt/oxd-server/conf/oxd-server.keystore
            name: oxd-keystore-file
            subPath: oxd-server.keystore
          - mountPath: /scripts
            name: update-lb-ip
      volumes:
      - name: oxd-keystore-file
        secret:
          secretName: oxdkeystorecm
      - name: update-lb-ip
        configMap:
          name: updatelbip
      hostAliases:
      - ip: NGINX_IP
        hostnames:
        - FQDN