# License terms and conditions for Gluu Cloud Native Edition:
# https://www.apache.org/licenses/LICENSE-2.0
# -- Nginx ingress definitions chart
ingress:
  enabled: true
  path: /
  # -- Enable Admin UI endpoints /identity
  adminUiEnabled: true
  # -- Enable endpoint /.well-known/openid-configuration
  openidConfigEnabled: true
  # -- Enable endpoint /.well-known/uma2-configuration
  uma2ConfigEnabled: true
  # -- Enable endpoint /.well-known/webfinger
  webfingerEnabled: true
  # -- Enable endpoint /.well-known/simple-web-discovery
  webdiscoveryEnabled: true
  # -- Enable endpoint /.well-known/scim-configuration
  scimConfigEnabled: false
  # -- Enable SCIM endpoints /scim
  scimEnabled: false
  # -- Enable endpoint /.well-known/fido-configuration
  u2fConfigEnabled: true
  # -- Enable endpoint /.well-known/fido2-configuration
  fido2ConfigEnabled: false
  # -- Enable Auth server endpoints /oxauth
  authServerEnabled: true
  # -- Enable casa endpoints /casa
  casaEnabled: true
  # -- Additional annotations that will be added across all ingress definitions in the format of {cert-manager.io/issuer: "letsencrypt-prod"}
  # Enable client certificate authentication
  # nginx-ingress.ingress.kubernetes.io/auth-tls-verify-client: "optional"
  # Create the secret containing the trusted ca certificates
  # nginx-ingress.ingress.kubernetes.io/auth-tls-secret: "gluu/tls-certificate"
  # Specify the verification depth in the client certificates chain
  # nginx-ingress.ingress.kubernetes.io/auth-tls-verify-depth: "1"
  # Specify if certificates are passed to upstream server
  # nginx-ingress.ingress.kubernetes.io/auth-tls-pass-certificate-to-upstream: "true"
  additionalAnnotations:
    # Required annotation below
    kubernetes.io/ingress.class: "nginx-ingress"
  hosts:
  - demoexample.gluu.org
  tls:
  - secretName: tls-certificate # DON'T change
    hosts:
    - demoexample.gluu.org
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 8080