apiVersion: v1
kind: PersistentVolume
metadata:
  name: opendj-pv
  labels:
    app: opendj
spec:
  capacity:
    storage: STORAGELDAP
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: LDAPVOLUMEID
    fsType: ext4