apiVersion: v1
kind: PersistentVolume
metadata:
  name: shared-shib-pv
  labels:
      type: shared-shib
spec:
  capacity:
    storage: STORAGESHAREDSHIB
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/shared-shibboleth-idp"
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: casa-pv
  labels:
      type: casa
spec:
  capacity:
    storage: STORAGECASA
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/casa"
    type: DirectoryOrCreate