apiVersion: v1
kind: PersistentVolume
metadata:
  name: opendj-pv
  labels:
    app: opendj
spec:
  capacity:
    storage: STORAGELDAP
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "HOME_DIR/opendj"
    type: DirectoryOrCreate