apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: opendj
spec:
  serviceName: opendj
  selector:
    matchLabels:
      app: opendj
  volumeClaimTemplates:
    - metadata:
        name: opendj-pvc
      spec:
        volumeName: opendj-pv
        storageClassName: ""
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: STORAGELDAP