# License terms and conditions:
# https://www.gluu.org/license/enterprise-edition/
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: opendj
spec:
  volumeClaimTemplates:
    - metadata:
        annotations:
          volume.beta.kubernetes.io/storage-class: "aws-efs"
        name: opendj-pvc
      spec:
        accessModes:
          - ReadWriteMany
        resources:
          requests:
            storage: STORAGELDAP
