# License terms and conditions for Gluu Cloud Native Edition:
# https://www.apache.org/licenses/LICENSE-2.0
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: opendj
spec:
  volumeClaimTemplates:
    - metadata:
        annotations:
          volume.beta.kubernetes.io/storage-class: "aws-efs"
        name: opendj-pvc
      spec:
        accessModes:
          - ReadWriteMany
        resources:
          requests:
            storage: STORAGELDAP
