# License terms and conditions for Gluu Cloud Native Edition:
# https://www.apache.org/licenses/LICENSE-2.0

usrEnvs: {}
#  normal:
#    variable1: value1
#  secret:
#    variable4: value4

image:
  repository: gluufederation/fido2
  tag: 4.2.3_01
  pullPolicy: Always
replicas: 1
#Resources for the deployment
requests:
  memory: 1000Mi
limits:
  memory: 1536Mi

livenessProbe:
  httpGet:
    path: /fido2/restv1/fido2/configuration
    port: http-fido2
  initialDelaySeconds: 25
  periodSeconds: 25
  timeoutSeconds: 5
readinessProbe:
  httpGet:
    path: /fido2/restv1/fido2/configuration
    port: http-fido2
  initialDelaySeconds: 30
  periodSeconds: 30
  timeoutSeconds: 5

service:
  fido2ServiceName: fido2
  name: http-fido2
  port: 8080

dnsPolicy: ""
dnsConfig: {}
  # options:
  #   - name: ndots
  #     value: "5"