# License terms and conditions:
# https://www.apache.org/licenses/LICENSE-2.0
# Used with Istio
apiVersion: v1
kind: Service
metadata:
    name: auth-server-key-rotation
spec:
    ports:
        - name: http
          port: 80
          targetPort: 8080
    selector:
        app: auth-server-key-rotation
    type: ClusterIP
