apiVersion: v1
kind: PersistentVolume
metadata:
  name: config-pv
  labels:
      config-init: config
spec:
  capacity:
    storage: STORAGECONFIG
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "HOME_DIR/config/db"
    type: DirectoryOrCreate