apiVersion: v1
kind: PersistentVolume
metadata:
  name: radius-pv
  labels:
    type: radius
spec:
  capacity:
    storage: STORAGERADIUS
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "HOME_DIR/radius/"
    type: DirectoryOrCreate