apiVersion: v2
name: ldap-backup
description: A backup strategy for LDAP
type: application
version: 1.4.0
appVersion: "4.2.3"
maintainers:
- name: Gluu
email: support@gluu.org
home: https://www.gluu.org


