apiVersion: v2
name: ldap-backup
description: A backup strategy for LDAP
type: application
version: 1.2.16
appVersion: 5.0.0
maintainers:
- name: Gluu
email: support@gluu.org
home: https://www.gluu.org


