apiVersion: v2
name: ldap-backup
description: A backup strategy for LDAP
type: application
version: 1.2.24
appVersion: 4.2.2
maintainers:
- name: Gluu
email: support@gluu.org
home: https://www.gluu.org


