name: microk8s
# This builds, packages and tests pygluu-kubernetes
on: [push]
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7]

    steps:
    - name: Checkout code
      uses: actions/checkout@master
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo python3 -m pip install --upgrade pip
        sudo pip3 install setuptools --upgrade
        sudo pip3 install pyOpenSSL --upgrade
        
    - name: Lint with flake8
      run: |
        sudo pip3 install flake8
        # stop the build if there are Python syntax errors or undefined names
        sudo flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        sudo flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Build Zipapp
      run: |
        sudo apt-get update
        sudo apt-get install build-essential
        sudo pip3 install shiv
        mkdir /home/runner/work/test
        cp -r ./* /home/runner/work/test/
        cd /home/runner/work/test/
        sudo make zipapp

    - name: Test 1 settings(LDAP)
      id: test1_settings
      run: |
        ip=$(ifconfig eth0 | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0.1')
        cat <<EOF > /home/runner/work/test/settings.json
        {
          "ACCEPT_GLUU_LICENSE": "Y",
          "GLUU_VERSION": "4.1",
          "GLUU_UPGRADE_TARGET_VERSION": "",
          "GLUU_HELM_RELEASE_NAME": "",
          "NGINX_INGRESS_RELEASE_NAME": "",
          "NGINX_INGRESS_NAMESPACE": "",
          "NODES_IPS": [
            "$ip"
          ],
          "NODES_ZONES": [],
          "NODES_NAMES": [],
          "NODE_SSH_KEY": "",
          "HOST_EXT_IP": "$ip",
          "VERIFY_EXT_IP": "",
          "AWS_LB_TYPE": "",
          "USE_ARN": "",
          "ARN_AWS_IAM": "",
          "LB_ADD": "",
          "DEPLOYMENT_ARCH": "microk8s",
          "PERSISTENCE_BACKEND": "ldap",
          "INSTALL_COUCHBASE": "",
          "COUCHBASE_NAMESPACE": "",
          "COUCHBASE_VOLUME_TYPE": "",
          "COUCHBASE_CLUSTER_NAME": "",
          "COUCHBASE_FQDN": "",
          "COUCHBASE_URL": "couchbase",
          "COUCHBASE_USER": "admin",
          "COUCHBASE_PASSWORD": "",
          "COUCHBASE_CRT": "",
          "COUCHBASE_SUBJECT_ALT_NAME": "",
          "COUCHBASE_CLUSTER_FILE_OVERRIDE": "",
          "COUCHBASE_USE_LOW_RESOURCES": "",
          "COUCHBASE_DATA_NODES": "",
          "COUCHBASE_QUERY_NODES": "",
          "COUCHBASE_INDEX_NODES": "",
          "COUCHBASE_SEARCH_EVENTING_ANALYTICS_NODES": "",
          "COUCHBASE_GENERAL_STORAGE": "",
          "COUCHBASE_DATA_STORAGE": "",
          "COUCHBASE_INDEX_STORAGE": "",
          "COUCHBASE_QUERY_STORAGE": "",
          "COUCHBASE_ANALYTICS_STORAGE": "",
          "NUMBER_OF_EXPECTED_USERS": "",
          "EXPECTED_TRANSACTIONS_PER_SEC": "",
          "USING_CODE_FLOW": "",
          "USING_SCIM_FLOW": "",
          "USING_RESOURCE_OWNER_PASSWORD_CRED_GRANT_FLOW": "",
          "DEPLOY_MULTI_CLUSTER": "",
          "HYBRID_LDAP_HELD_DATA": "",
          "LDAP_VOLUME": "",
          "LDAP_VOLUME_TYPE": 1,
          "LDAP_STATIC_VOLUME_ID": "",
          "LDAP_STATIC_DISK_URI": "",
          "OXTRUST_OXSHIBBOLETH_SHARED_VOLUME_TYPE": "",
          "ACCEPT_EFS_NOTES": "",
          "EFS_FILE_SYSTEM_ID": "",
          "EFS_AWS_REGION": "",
          "EFS_DNS": "",
          "GLUU_CACHE_TYPE": "NATIVE_PERSISTENCE",
          "GLUU_NAMESPACE": "gluu",
          "GLUU_FQDN": "demoexample.gluu.org",
          "COUNTRY_CODE": "US",
          "STATE": "TX",
          "EMAIL": "support@gluu.org",
          "CITY": "Austin",
          "ORG_NAME": "Gluu",
          "GMAIL_ACCOUNT": "",
          "GOOGLE_NODE_HOME_DIR": "",
          "IS_GLUU_FQDN_REGISTERED": "N",
          "LDAP_PW": "nTB5#|",
          "ADMIN_PW": "@4n,Js",
          "OXD_SERVER_PW": "n8H0NKuGTXsn",
          "OXD_APPLICATION_KEYSTORE_CN": "oxd-server",
          "OXD_ADMIN_KEYSTORE_CN": "oxd-server",
          "LDAP_STORAGE_SIZE": "4Gi",
          "OXTRUST_OXSHIBBOLETH_SHARED_STORAGE_SIZE": "4Gi",
          "NFS_STORAGE_SIZE": "4Gi",
          "OXAUTH_REPLICAS": 1,
          "OXTRUST_REPLICAS": 1,
          "LDAP_REPLICAS": 1,
          "OXSHIBBOLETH_REPLICAS": 1,
          "OXPASSPORT_REPLICAS": 1,
          "OXD_SERVER_REPLICAS": 1,
          "CASA_REPLICAS": 1,
          "RADIUS_REPLICAS": 1,
          "ENABLE_OXTRUST_API": "N",
          "ENABLE_OXTRUST_TEST_MODE": "N",
          "ENABLE_CACHE_REFRESH": "N",
          "ENABLE_OXD": "Y",
          "ENABLE_RADIUS": "Y",
          "ENABLE_OXPASSPORT": "Y",
          "ENABLE_OXSHIBBOLETH": "Y",
          "ENABLE_CASA": "N",
          "ENABLE_KEY_ROTATE": "Y",
          "ENABLE_OXTRUST_API_BOOLEAN": "true",
          "ENABLE_OXTRUST_TEST_MODE_BOOLEAN": "false",
          "ENABLE_RADIUS_BOOLEAN": "true",
          "ENABLE_OXPASSPORT_BOOLEAN": "true",
          "ENABLE_CASA_BOOLEAN": "false",
          "ENABLE_SAML_BOOLEAN": "true",
          "EDIT_IMAGE_NAMES_TAGS": "N",
          "CASA_IMAGE_NAME": "gluufederation/casa",
          "CASA_IMAGE_TAG": "4.2.0_dev",
          "CONFIG_IMAGE_NAME": "gluufederation/config-init",
          "CONFIG_IMAGE_TAG": "4.1.0_dev",
          "CACHE_REFRESH_ROTATE_IMAGE_NAME": "gluufederation/cr-rotate",
          "CACHE_REFRESH_ROTATE_IMAGE_TAG": "4.1.0_dev",
          "KEY_ROTATE_IMAGE_NAME": "gluufederation/key-rotation",
          "KEY_ROTATE_IMAGE_TAG": "4.1.0_dev",
          "LDAP_IMAGE_NAME": "gluufederation/wrends",
          "LDAP_IMAGE_TAG": "4.1.0_dev",
          "OXAUTH_IMAGE_NAME": "gluufederation/oxauth",
          "OXAUTH_IMAGE_TAG": "4.1.0_dev",
          "OXD_IMAGE_NAME": "gluufederation/oxd-server",
          "OXD_IMAGE_TAG": "4.1.0_dev",
          "OXPASSPORT_IMAGE_NAME": "gluufederation/oxpassport",
          "OXPASSPORT_IMAGE_TAG": "4.1.0_dev",
          "OXSHIBBOLETH_IMAGE_NAME": "gluufederation/oxshibboleth",
          "OXSHIBBOLETH_IMAGE_TAG": "4.1.0_dev",
          "OXTRUST_IMAGE_NAME": "gluufederation/oxtrust",
          "OXTRUST_IMAGE_TAG": "4.1.0_dev",
          "PERSISTENCE_IMAGE_NAME": "gluufederation/persistence",
          "PERSISTENCE_IMAGE_TAG": "4.1.0_dev",
          "RADIUS_IMAGE_NAME": "gluufederation/radius",
          "RADIUS_IMAGE_TAG": "4.1.0_dev",
          "UPGRADE_IMAGE_NAME": "gluufederation/upgrade",
          "UPGRADE_IMAGE_TAG": "4.1.0_dev",
          "CONFIRM_PARAMS": "Y"
        }
        EOF
        
    - name: Install microk8s
      run: |
        sudo snap install microk8s --classic
        sudo microk8s.status --wait-ready
        sudo microk8s.enable dns registry ingress
        
    - name: Test Pygluu kubernetes
      id: test_kubernetes
      run: |
          cd /home/runner/work/test/
          sudo ./pygluu-kubernetes.pyz install
