# License terms and conditions for Gluu Cloud Native Edition:
# https://www.apache.org/licenses/LICENSE-2.0
# Default values for oxd-server.
#HorizontalPodAutoscaler
hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
  # metrics if targetCPUUtilizationPercentage is not set
  metrics: []
  #Scaling Policies
  behavior: {}

usrEnvs: {}
#  normal:
#    variable1: value1
#  secret:
#    variable4: value4

replicas: 1
service:
  # This must match config.configMap.gluuOxdApplicationCertCn
  oxdServerServiceName: oxd-server
image:
  repository: gluufederation/oxd-server
  tag: 4.3.0_b1
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

livenessProbe:
  exec:
    command:
      - curl
      - -k
      - https://localhost:8443/health-check
  initialDelaySeconds: 30
  periodSeconds: 30
  timeoutSeconds: 5
readinessProbe:
  exec:
    command:
      - curl
      - -k
      - https://localhost:8443/health-check
  initialDelaySeconds: 25
  periodSeconds: 25
  timeoutSeconds: 5

nodeSelector: {}

tolerations: []

affinity: {}
volumes: []
  # Configure any additional volumes need to be attached to the pod
  # - name: mycustomcert
  #   secret:
  #     secretName: mycustomsecret
volumeMounts: []
  # Configure any additional volumesMounts that need to be attached to the containers
  # - name: mycustomcert
  #   mountPath: /etc/certs
dnsPolicy: ""
dnsConfig: {}
  # options:
  #   - name: ndots
  #     value: "5"

# -- Resource specs.
resources:
  limits:
    # -- CPU limit.
    cpu: 1000m
    # -- Memory limit.
    memory: 400Mi
  requests:
    # -- CPU request.
    cpu: 1000m
    # -- Memory request.
    memory: 400Mi